// Generated by gencpp from file alicia_flexible_grasp_supervisor/CartesianJog.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_CARTESIANJOG_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_CARTESIANJOG_H

#include <ros/service_traits.h>


#include <alicia_flexible_grasp_supervisor/CartesianJogRequest.h>
#include <alicia_flexible_grasp_supervisor/CartesianJogResponse.h>


namespace alicia_flexible_grasp_supervisor
{

struct CartesianJog
{

typedef CartesianJogRequest Request;
typedef CartesianJogResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CartesianJog
} // namespace alicia_flexible_grasp_supervisor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::CartesianJog > {
  static const char* value()
  {
    return "fe30d6dd3aeb27b001869b9c8844bee4";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::CartesianJog&) { return value(); }
};

template<>
struct DataType< ::alicia_flexible_grasp_supervisor::CartesianJog > {
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/CartesianJog";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::CartesianJog&) { return value(); }
};


// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::CartesianJogRequest> should match
// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::CartesianJog >
template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::CartesianJogRequest>
{
  static const char* value()
  {
    return MD5Sum< ::alicia_flexible_grasp_supervisor::CartesianJog >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::CartesianJogRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::alicia_flexible_grasp_supervisor::CartesianJogRequest> should match
// service_traits::DataType< ::alicia_flexible_grasp_supervisor::CartesianJog >
template<>
struct DataType< ::alicia_flexible_grasp_supervisor::CartesianJogRequest>
{
  static const char* value()
  {
    return DataType< ::alicia_flexible_grasp_supervisor::CartesianJog >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::CartesianJogRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::CartesianJogResponse> should match
// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::CartesianJog >
template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::CartesianJogResponse>
{
  static const char* value()
  {
    return MD5Sum< ::alicia_flexible_grasp_supervisor::CartesianJog >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::CartesianJogResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::alicia_flexible_grasp_supervisor::CartesianJogResponse> should match
// service_traits::DataType< ::alicia_flexible_grasp_supervisor::CartesianJog >
template<>
struct DataType< ::alicia_flexible_grasp_supervisor::CartesianJogResponse>
{
  static const char* value()
  {
    return DataType< ::alicia_flexible_grasp_supervisor::CartesianJog >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::CartesianJogResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_CARTESIANJOG_H
