// Generated by gencpp from file alicia_flexible_grasp_supervisor/CartesianJogRequest.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_CARTESIANJOGREQUEST_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_CARTESIANJOGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alicia_flexible_grasp_supervisor
{
template <class ContainerAllocator>
struct CartesianJogRequest_
{
  typedef CartesianJogRequest_<ContainerAllocator> Type;

  CartesianJogRequest_()
    : dx(0.0)
    , dy(0.0)
    , dz(0.0)
    , droll(0.0)
    , dpitch(0.0)
    , dyaw(0.0)
    , execute(false)  {
    }
  CartesianJogRequest_(const ContainerAllocator& _alloc)
    : dx(0.0)
    , dy(0.0)
    , dz(0.0)
    , droll(0.0)
    , dpitch(0.0)
    , dyaw(0.0)
    , execute(false)  {
  (void)_alloc;
    }



   typedef double _dx_type;
  _dx_type dx;

   typedef double _dy_type;
  _dy_type dy;

   typedef double _dz_type;
  _dz_type dz;

   typedef double _droll_type;
  _droll_type droll;

   typedef double _dpitch_type;
  _dpitch_type dpitch;

   typedef double _dyaw_type;
  _dyaw_type dyaw;

   typedef uint8_t _execute_type;
  _execute_type execute;





  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CartesianJogRequest_

typedef ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<std::allocator<void> > CartesianJogRequest;

typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::CartesianJogRequest > CartesianJogRequestPtr;
typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::CartesianJogRequest const> CartesianJogRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator2> & rhs)
{
  return lhs.dx == rhs.dx &&
    lhs.dy == rhs.dy &&
    lhs.dz == rhs.dz &&
    lhs.droll == rhs.droll &&
    lhs.dpitch == rhs.dpitch &&
    lhs.dyaw == rhs.dyaw &&
    lhs.execute == rhs.execute;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alicia_flexible_grasp_supervisor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "563a5d9842521889e912b333b62d4ffd";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x563a5d9842521889ULL;
  static const uint64_t static_value2 = 0xe912b333b62d4ffdULL;
};

template<class ContainerAllocator>
struct DataType< ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/CartesianJogRequest";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 dx\n"
"float64 dy\n"
"float64 dz\n"
"float64 droll\n"
"float64 dpitch\n"
"float64 dyaw\n"
"bool execute\n"
;
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dx);
      stream.next(m.dy);
      stream.next(m.dz);
      stream.next(m.droll);
      stream.next(m.dpitch);
      stream.next(m.dyaw);
      stream.next(m.execute);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CartesianJogRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alicia_flexible_grasp_supervisor::CartesianJogRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "dx: ";
    Printer<double>::stream(s, indent + "  ", v.dx);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dy: ";
    Printer<double>::stream(s, indent + "  ", v.dy);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dz: ";
    Printer<double>::stream(s, indent + "  ", v.dz);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "droll: ";
    Printer<double>::stream(s, indent + "  ", v.droll);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dpitch: ";
    Printer<double>::stream(s, indent + "  ", v.dpitch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dyaw: ";
    Printer<double>::stream(s, indent + "  ", v.dyaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "execute: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.execute);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_CARTESIANJOGREQUEST_H
