// Generated by gencpp from file alicia_flexible_grasp_supervisor/GraspState.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_GRASPSTATE_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_GRASPSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace alicia_flexible_grasp_supervisor
{
template <class ContainerAllocator>
struct GraspState_
{
  typedef GraspState_<ContainerAllocator> Type;

  GraspState_()
    : header()
    , state(0)
    , state_name()
    , running(false)
    , success(false)
    , message()
    , current_force(0.0)
    , target_force(0.0)
    , object_pose_base()
    , target_pose()  {
    }
  GraspState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(0)
    , state_name(_alloc)
    , running(false)
    , success(false)
    , message(_alloc)
    , current_force(0.0)
    , target_force(0.0)
    , object_pose_base(_alloc)
    , target_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _state_type;
  _state_type state;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_name_type;
  _state_name_type state_name;

   typedef uint8_t _running_type;
  _running_type running;

   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef float _current_force_type;
  _current_force_type current_force;

   typedef float _target_force_type;
  _target_force_type target_force;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _object_pose_base_type;
  _object_pose_base_type object_pose_base;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target_pose_type;
  _target_pose_type target_pose;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(IDLE)
  #undef IDLE
#endif
#if defined(_WIN32) && defined(SEARCH_OBJECT)
  #undef SEARCH_OBJECT
#endif
#if defined(_WIN32) && defined(ESTIMATE_POSE)
  #undef ESTIMATE_POSE
#endif
#if defined(_WIN32) && defined(PLAN_PREGRASP)
  #undef PLAN_PREGRASP
#endif
#if defined(_WIN32) && defined(MOVE_PREGRASP)
  #undef MOVE_PREGRASP
#endif
#if defined(_WIN32) && defined(APPROACH_OBJECT)
  #undef APPROACH_OBJECT
#endif
#if defined(_WIN32) && defined(COMPLIANT_CLOSE)
  #undef COMPLIANT_CLOSE
#endif
#if defined(_WIN32) && defined(GRASP_VERIFY)
  #undef GRASP_VERIFY
#endif
#if defined(_WIN32) && defined(LIFT_OBJECT)
  #undef LIFT_OBJECT
#endif
#if defined(_WIN32) && defined(PLACE_OBJECT)
  #undef PLACE_OBJECT
#endif
#if defined(_WIN32) && defined(RELEASE_OBJECT)
  #undef RELEASE_OBJECT
#endif
#if defined(_WIN32) && defined(SUCCESS)
  #undef SUCCESS
#endif
#if defined(_WIN32) && defined(FAILED)
  #undef FAILED
#endif
#if defined(_WIN32) && defined(EMERGENCY_STOP)
  #undef EMERGENCY_STOP
#endif

  enum {
    IDLE = 0u,
    SEARCH_OBJECT = 1u,
    ESTIMATE_POSE = 2u,
    PLAN_PREGRASP = 3u,
    MOVE_PREGRASP = 4u,
    APPROACH_OBJECT = 5u,
    COMPLIANT_CLOSE = 6u,
    GRASP_VERIFY = 7u,
    LIFT_OBJECT = 8u,
    PLACE_OBJECT = 9u,
    RELEASE_OBJECT = 10u,
    SUCCESS = 11u,
    FAILED = 12u,
    EMERGENCY_STOP = 13u,
  };


  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator> const> ConstPtr;

}; // struct GraspState_

typedef ::alicia_flexible_grasp_supervisor::GraspState_<std::allocator<void> > GraspState;

typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::GraspState > GraspStatePtr;
typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::GraspState const> GraspStateConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.state == rhs.state &&
    lhs.state_name == rhs.state_name &&
    lhs.running == rhs.running &&
    lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.current_force == rhs.current_force &&
    lhs.target_force == rhs.target_force &&
    lhs.object_pose_base == rhs.object_pose_base &&
    lhs.target_pose == rhs.target_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alicia_flexible_grasp_supervisor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "75215c45032076e51dbd82164d6951cb";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x75215c45032076e5ULL;
  static const uint64_t static_value2 = 0x1dbd82164d6951cbULL;
};

template<class ContainerAllocator>
struct DataType< ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/GraspState";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint8 IDLE=0\n"
"uint8 SEARCH_OBJECT=1\n"
"uint8 ESTIMATE_POSE=2\n"
"uint8 PLAN_PREGRASP=3\n"
"uint8 MOVE_PREGRASP=4\n"
"uint8 APPROACH_OBJECT=5\n"
"uint8 COMPLIANT_CLOSE=6\n"
"uint8 GRASP_VERIFY=7\n"
"uint8 LIFT_OBJECT=8\n"
"uint8 PLACE_OBJECT=9\n"
"uint8 RELEASE_OBJECT=10\n"
"uint8 SUCCESS=11\n"
"uint8 FAILED=12\n"
"uint8 EMERGENCY_STOP=13\n"
"uint8 state\n"
"string state_name\n"
"bool running\n"
"bool success\n"
"string message\n"
"float32 current_force\n"
"float32 target_force\n"
"geometry_msgs/Pose object_pose_base\n"
"geometry_msgs/Pose target_pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
      stream.next(m.state_name);
      stream.next(m.running);
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.current_force);
      stream.next(m.target_force);
      stream.next(m.object_pose_base);
      stream.next(m.target_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraspState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alicia_flexible_grasp_supervisor::GraspState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state_name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "running: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.running);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "current_force: ";
    Printer<float>::stream(s, indent + "  ", v.current_force);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_force: ";
    Printer<float>::stream(s, indent + "  ", v.target_force);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "object_pose_base: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.object_pose_base);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_GRASPSTATE_H
