// Generated by gencpp from file alicia_flexible_grasp_supervisor/Grasp6DPlan.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_GRASP6DPLAN_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_GRASP6DPLAN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <alicia_flexible_grasp_supervisor/ObjectGeometry.h>

namespace alicia_flexible_grasp_supervisor
{
template <class ContainerAllocator>
struct Grasp6DPlan_
{
  typedef Grasp6DPlan_<ContainerAllocator> Type;

  Grasp6DPlan_()
    : header()
    , valid(false)
    , poses()
    , score(0.0)
    , candidate_width_m(0.0)
    , required_open_width_m(0.0)
    , object_geometry()
    , model_choice()
    , plan_id()
    , diagnostic()  {
    }
  Grasp6DPlan_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , valid(false)
    , poses(_alloc)
    , score(0.0)
    , candidate_width_m(0.0)
    , required_open_width_m(0.0)
    , object_geometry(_alloc)
    , model_choice(_alloc)
    , plan_id(_alloc)
    , diagnostic(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _valid_type;
  _valid_type valid;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose_<ContainerAllocator> >> _poses_type;
  _poses_type poses;

   typedef float _score_type;
  _score_type score;

   typedef float _candidate_width_m_type;
  _candidate_width_m_type candidate_width_m;

   typedef float _required_open_width_m_type;
  _required_open_width_m_type required_open_width_m;

   typedef  ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator>  _object_geometry_type;
  _object_geometry_type object_geometry;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _model_choice_type;
  _model_choice_type model_choice;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _plan_id_type;
  _plan_id_type plan_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _diagnostic_type;
  _diagnostic_type diagnostic;





  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator> const> ConstPtr;

}; // struct Grasp6DPlan_

typedef ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<std::allocator<void> > Grasp6DPlan;

typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::Grasp6DPlan > Grasp6DPlanPtr;
typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::Grasp6DPlan const> Grasp6DPlanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.valid == rhs.valid &&
    lhs.poses == rhs.poses &&
    lhs.score == rhs.score &&
    lhs.candidate_width_m == rhs.candidate_width_m &&
    lhs.required_open_width_m == rhs.required_open_width_m &&
    lhs.object_geometry == rhs.object_geometry &&
    lhs.model_choice == rhs.model_choice &&
    lhs.plan_id == rhs.plan_id &&
    lhs.diagnostic == rhs.diagnostic;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alicia_flexible_grasp_supervisor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a90c722154d42b08b0800cd88d52ff9d";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa90c722154d42b08ULL;
  static const uint64_t static_value2 = 0xb0800cd88d52ff9dULL;
};

template<class ContainerAllocator>
struct DataType< ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/Grasp6DPlan";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"bool valid\n"
"geometry_msgs/Pose[] poses\n"
"float32 score\n"
"float32 candidate_width_m\n"
"float32 required_open_width_m\n"
"alicia_flexible_grasp_supervisor/ObjectGeometry object_geometry\n"
"string model_choice\n"
"string plan_id\n"
"string diagnostic\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: alicia_flexible_grasp_supervisor/ObjectGeometry\n"
"std_msgs/Header header\n"
"bool valid\n"
"string label\n"
"string source_mode\n"
"geometry_msgs/Pose pose_base\n"
"geometry_msgs/Vector3 size_xyz_m\n"
"geometry_msgs/Vector3 support_normal_base\n"
"float32 support_offset_m\n"
"uint32 valid_depth_points\n"
"float32 valid_depth_ratio\n"
"float32 depth_mad_m\n"
"uint32 fused_frames\n"
"float32 support_inlier_ratio\n"
"uint32 object_point_count\n"
"string failure_reason\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.valid);
      stream.next(m.poses);
      stream.next(m.score);
      stream.next(m.candidate_width_m);
      stream.next(m.required_open_width_m);
      stream.next(m.object_geometry);
      stream.next(m.model_choice);
      stream.next(m.plan_id);
      stream.next(m.diagnostic);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Grasp6DPlan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alicia_flexible_grasp_supervisor::Grasp6DPlan_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "poses: ";
    if (v.poses.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.poses[i]);
    }
    if (v.poses.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "score: ";
    Printer<float>::stream(s, indent + "  ", v.score);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "candidate_width_m: ";
    Printer<float>::stream(s, indent + "  ", v.candidate_width_m);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "required_open_width_m: ";
    Printer<float>::stream(s, indent + "  ", v.required_open_width_m);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "object_geometry: ";
    Printer< ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator> >::stream(s, indent + "  ", v.object_geometry);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "model_choice: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.model_choice);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "plan_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.plan_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "diagnostic: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.diagnostic);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_GRASP6DPLAN_H
