// Generated by gencpp from file alicia_flexible_grasp_supervisor/ObjectGeometry.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_OBJECTGEOMETRY_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_OBJECTGEOMETRY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace alicia_flexible_grasp_supervisor
{
template <class ContainerAllocator>
struct ObjectGeometry_
{
  typedef ObjectGeometry_<ContainerAllocator> Type;

  ObjectGeometry_()
    : header()
    , valid(false)
    , label()
    , source_mode()
    , pose_base()
    , size_xyz_m()
    , support_normal_base()
    , support_offset_m(0.0)
    , valid_depth_points(0)
    , valid_depth_ratio(0.0)
    , depth_mad_m(0.0)
    , fused_frames(0)
    , support_inlier_ratio(0.0)
    , object_point_count(0)
    , failure_reason()  {
    }
  ObjectGeometry_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , valid(false)
    , label(_alloc)
    , source_mode(_alloc)
    , pose_base(_alloc)
    , size_xyz_m(_alloc)
    , support_normal_base(_alloc)
    , support_offset_m(0.0)
    , valid_depth_points(0)
    , valid_depth_ratio(0.0)
    , depth_mad_m(0.0)
    , fused_frames(0)
    , support_inlier_ratio(0.0)
    , object_point_count(0)
    , failure_reason(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _valid_type;
  _valid_type valid;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _label_type;
  _label_type label;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _source_mode_type;
  _source_mode_type source_mode;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_base_type;
  _pose_base_type pose_base;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _size_xyz_m_type;
  _size_xyz_m_type size_xyz_m;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _support_normal_base_type;
  _support_normal_base_type support_normal_base;

   typedef float _support_offset_m_type;
  _support_offset_m_type support_offset_m;

   typedef uint32_t _valid_depth_points_type;
  _valid_depth_points_type valid_depth_points;

   typedef float _valid_depth_ratio_type;
  _valid_depth_ratio_type valid_depth_ratio;

   typedef float _depth_mad_m_type;
  _depth_mad_m_type depth_mad_m;

   typedef uint32_t _fused_frames_type;
  _fused_frames_type fused_frames;

   typedef float _support_inlier_ratio_type;
  _support_inlier_ratio_type support_inlier_ratio;

   typedef uint32_t _object_point_count_type;
  _object_point_count_type object_point_count;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _failure_reason_type;
  _failure_reason_type failure_reason;





  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectGeometry_

typedef ::alicia_flexible_grasp_supervisor::ObjectGeometry_<std::allocator<void> > ObjectGeometry;

typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::ObjectGeometry > ObjectGeometryPtr;
typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::ObjectGeometry const> ObjectGeometryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.valid == rhs.valid &&
    lhs.label == rhs.label &&
    lhs.source_mode == rhs.source_mode &&
    lhs.pose_base == rhs.pose_base &&
    lhs.size_xyz_m == rhs.size_xyz_m &&
    lhs.support_normal_base == rhs.support_normal_base &&
    lhs.support_offset_m == rhs.support_offset_m &&
    lhs.valid_depth_points == rhs.valid_depth_points &&
    lhs.valid_depth_ratio == rhs.valid_depth_ratio &&
    lhs.depth_mad_m == rhs.depth_mad_m &&
    lhs.fused_frames == rhs.fused_frames &&
    lhs.support_inlier_ratio == rhs.support_inlier_ratio &&
    lhs.object_point_count == rhs.object_point_count &&
    lhs.failure_reason == rhs.failure_reason;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alicia_flexible_grasp_supervisor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be6e291b8f028ecb31c9e9f8f891dc32";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe6e291b8f028ecbULL;
  static const uint64_t static_value2 = 0x31c9e9f8f891dc32ULL;
};

template<class ContainerAllocator>
struct DataType< ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/ObjectGeometry";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"bool valid\n"
"string label\n"
"string source_mode\n"
"geometry_msgs/Pose pose_base\n"
"geometry_msgs/Vector3 size_xyz_m\n"
"geometry_msgs/Vector3 support_normal_base\n"
"float32 support_offset_m\n"
"uint32 valid_depth_points\n"
"float32 valid_depth_ratio\n"
"float32 depth_mad_m\n"
"uint32 fused_frames\n"
"float32 support_inlier_ratio\n"
"uint32 object_point_count\n"
"string failure_reason\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.valid);
      stream.next(m.label);
      stream.next(m.source_mode);
      stream.next(m.pose_base);
      stream.next(m.size_xyz_m);
      stream.next(m.support_normal_base);
      stream.next(m.support_offset_m);
      stream.next(m.valid_depth_points);
      stream.next(m.valid_depth_ratio);
      stream.next(m.depth_mad_m);
      stream.next(m.fused_frames);
      stream.next(m.support_inlier_ratio);
      stream.next(m.object_point_count);
      stream.next(m.failure_reason);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectGeometry_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alicia_flexible_grasp_supervisor::ObjectGeometry_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.label);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "source_mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.source_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose_base: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose_base);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "size_xyz_m: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.size_xyz_m);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "support_normal_base: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.support_normal_base);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "support_offset_m: ";
    Printer<float>::stream(s, indent + "  ", v.support_offset_m);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "valid_depth_points: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.valid_depth_points);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "valid_depth_ratio: ";
    Printer<float>::stream(s, indent + "  ", v.valid_depth_ratio);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "depth_mad_m: ";
    Printer<float>::stream(s, indent + "  ", v.depth_mad_m);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fused_frames: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.fused_frames);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "support_inlier_ratio: ";
    Printer<float>::stream(s, indent + "  ", v.support_inlier_ratio);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "object_point_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.object_point_count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "failure_reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.failure_reason);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_OBJECTGEOMETRY_H
