// Generated by gencpp from file alicia_flexible_grasp_supervisor/ObjectPose.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_OBJECTPOSE_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_OBJECTPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>

namespace alicia_flexible_grasp_supervisor
{
template <class ContainerAllocator>
struct ObjectPose_
{
  typedef ObjectPose_<ContainerAllocator> Type;

  ObjectPose_()
    : header()
    , detected(false)
    , label()
    , confidence(0.0)
    , u(0)
    , v(0)
    , bbox_x(0)
    , bbox_y(0)
    , bbox_width(0)
    , bbox_height(0)
    , depth_m(0.0)
    , pose_camera()
    , pose_base()  {
    }
  ObjectPose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detected(false)
    , label(_alloc)
    , confidence(0.0)
    , u(0)
    , v(0)
    , bbox_x(0)
    , bbox_y(0)
    , bbox_width(0)
    , bbox_height(0)
    , depth_m(0.0)
    , pose_camera(_alloc)
    , pose_base(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _detected_type;
  _detected_type detected;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _label_type;
  _label_type label;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef uint32_t _u_type;
  _u_type u;

   typedef uint32_t _v_type;
  _v_type v;

   typedef uint32_t _bbox_x_type;
  _bbox_x_type bbox_x;

   typedef uint32_t _bbox_y_type;
  _bbox_y_type bbox_y;

   typedef uint32_t _bbox_width_type;
  _bbox_width_type bbox_width;

   typedef uint32_t _bbox_height_type;
  _bbox_height_type bbox_height;

   typedef float _depth_m_type;
  _depth_m_type depth_m;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_camera_type;
  _pose_camera_type pose_camera;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_base_type;
  _pose_base_type pose_base;





  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectPose_

typedef ::alicia_flexible_grasp_supervisor::ObjectPose_<std::allocator<void> > ObjectPose;

typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::ObjectPose > ObjectPosePtr;
typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::ObjectPose const> ObjectPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detected == rhs.detected &&
    lhs.label == rhs.label &&
    lhs.confidence == rhs.confidence &&
    lhs.u == rhs.u &&
    lhs.v == rhs.v &&
    lhs.bbox_x == rhs.bbox_x &&
    lhs.bbox_y == rhs.bbox_y &&
    lhs.bbox_width == rhs.bbox_width &&
    lhs.bbox_height == rhs.bbox_height &&
    lhs.depth_m == rhs.depth_m &&
    lhs.pose_camera == rhs.pose_camera &&
    lhs.pose_base == rhs.pose_base;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alicia_flexible_grasp_supervisor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d3731316703d38acb9f83ae0dd46e90";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d3731316703d38aULL;
  static const uint64_t static_value2 = 0xcb9f83ae0dd46e90ULL;
};

template<class ContainerAllocator>
struct DataType< ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/ObjectPose";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"bool detected\n"
"string label\n"
"float32 confidence\n"
"uint32 u\n"
"uint32 v\n"
"uint32 bbox_x\n"
"uint32 bbox_y\n"
"uint32 bbox_width\n"
"uint32 bbox_height\n"
"float32 depth_m\n"
"geometry_msgs/PoseStamped pose_camera\n"
"geometry_msgs/PoseStamped pose_base\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detected);
      stream.next(m.label);
      stream.next(m.confidence);
      stream.next(m.u);
      stream.next(m.v);
      stream.next(m.bbox_x);
      stream.next(m.bbox_y);
      stream.next(m.bbox_width);
      stream.next(m.bbox_height);
      stream.next(m.depth_m);
      stream.next(m.pose_camera);
      stream.next(m.pose_base);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alicia_flexible_grasp_supervisor::ObjectPose_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.detected);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.label);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "u: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.u);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "v: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.v);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bbox_x: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.bbox_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bbox_y: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.bbox_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bbox_width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.bbox_width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bbox_height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.bbox_height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "depth_m: ";
    Printer<float>::stream(s, indent + "  ", v.depth_m);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose_camera: ";
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose_camera);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose_base: ";
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose_base);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_OBJECTPOSE_H
