// Generated by gencpp from file alicia_flexible_grasp_supervisor/SafetyState.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SAFETYSTATE_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SAFETYSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace alicia_flexible_grasp_supervisor
{
template <class ContainerAllocator>
struct SafetyState_
{
  typedef SafetyState_<ContainerAllocator> Type;

  SafetyState_()
    : header()
    , ok(false)
    , emergency_stop(false)
    , force_over_limit(false)
    , robot_timeout(false)
    , tactile_timeout(false)
    , camera_timeout(false)
    , planning_failed(false)
    , level()
    , message()  {
    }
  SafetyState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ok(false)
    , emergency_stop(false)
    , force_over_limit(false)
    , robot_timeout(false)
    , tactile_timeout(false)
    , camera_timeout(false)
    , planning_failed(false)
    , level(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _ok_type;
  _ok_type ok;

   typedef uint8_t _emergency_stop_type;
  _emergency_stop_type emergency_stop;

   typedef uint8_t _force_over_limit_type;
  _force_over_limit_type force_over_limit;

   typedef uint8_t _robot_timeout_type;
  _robot_timeout_type robot_timeout;

   typedef uint8_t _tactile_timeout_type;
  _tactile_timeout_type tactile_timeout;

   typedef uint8_t _camera_timeout_type;
  _camera_timeout_type camera_timeout;

   typedef uint8_t _planning_failed_type;
  _planning_failed_type planning_failed;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _level_type;
  _level_type level;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator> const> ConstPtr;

}; // struct SafetyState_

typedef ::alicia_flexible_grasp_supervisor::SafetyState_<std::allocator<void> > SafetyState;

typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::SafetyState > SafetyStatePtr;
typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::SafetyState const> SafetyStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ok == rhs.ok &&
    lhs.emergency_stop == rhs.emergency_stop &&
    lhs.force_over_limit == rhs.force_over_limit &&
    lhs.robot_timeout == rhs.robot_timeout &&
    lhs.tactile_timeout == rhs.tactile_timeout &&
    lhs.camera_timeout == rhs.camera_timeout &&
    lhs.planning_failed == rhs.planning_failed &&
    lhs.level == rhs.level &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alicia_flexible_grasp_supervisor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d422c2c3e9933ef7c15274804ca0c2f7";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd422c2c3e9933ef7ULL;
  static const uint64_t static_value2 = 0xc15274804ca0c2f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/SafetyState";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"bool ok\n"
"bool emergency_stop\n"
"bool force_over_limit\n"
"bool robot_timeout\n"
"bool tactile_timeout\n"
"bool camera_timeout\n"
"bool planning_failed\n"
"string level\n"
"string message\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ok);
      stream.next(m.emergency_stop);
      stream.next(m.force_over_limit);
      stream.next(m.robot_timeout);
      stream.next(m.tactile_timeout);
      stream.next(m.camera_timeout);
      stream.next(m.planning_failed);
      stream.next(m.level);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SafetyState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alicia_flexible_grasp_supervisor::SafetyState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ok);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "emergency_stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emergency_stop);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "force_over_limit: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.force_over_limit);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "robot_timeout: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.robot_timeout);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tactile_timeout: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tactile_timeout);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "camera_timeout: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.camera_timeout);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "planning_failed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.planning_failed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "level: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.level);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SAFETYSTATE_H
