// Generated by gencpp from file alicia_flexible_grasp_supervisor/SetForceParams.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SETFORCEPARAMS_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SETFORCEPARAMS_H

#include <ros/service_traits.h>


#include <alicia_flexible_grasp_supervisor/SetForceParamsRequest.h>
#include <alicia_flexible_grasp_supervisor/SetForceParamsResponse.h>


namespace alicia_flexible_grasp_supervisor
{

struct SetForceParams
{

typedef SetForceParamsRequest Request;
typedef SetForceParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetForceParams
} // namespace alicia_flexible_grasp_supervisor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::SetForceParams > {
  static const char* value()
  {
    return "5ef41667b487a681d2b7b91f8a1e0b10";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::SetForceParams&) { return value(); }
};

template<>
struct DataType< ::alicia_flexible_grasp_supervisor::SetForceParams > {
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/SetForceParams";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::SetForceParams&) { return value(); }
};


// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::SetForceParamsRequest> should match
// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::SetForceParams >
template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::SetForceParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::alicia_flexible_grasp_supervisor::SetForceParams >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::SetForceParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::alicia_flexible_grasp_supervisor::SetForceParamsRequest> should match
// service_traits::DataType< ::alicia_flexible_grasp_supervisor::SetForceParams >
template<>
struct DataType< ::alicia_flexible_grasp_supervisor::SetForceParamsRequest>
{
  static const char* value()
  {
    return DataType< ::alicia_flexible_grasp_supervisor::SetForceParams >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::SetForceParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::SetForceParamsResponse> should match
// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::SetForceParams >
template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::SetForceParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::alicia_flexible_grasp_supervisor::SetForceParams >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::SetForceParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::alicia_flexible_grasp_supervisor::SetForceParamsResponse> should match
// service_traits::DataType< ::alicia_flexible_grasp_supervisor::SetForceParams >
template<>
struct DataType< ::alicia_flexible_grasp_supervisor::SetForceParamsResponse>
{
  static const char* value()
  {
    return DataType< ::alicia_flexible_grasp_supervisor::SetForceParams >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::SetForceParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SETFORCEPARAMS_H
