// Generated by gencpp from file alicia_flexible_grasp_supervisor/SetForceParamsRequest.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SETFORCEPARAMSREQUEST_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SETFORCEPARAMSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alicia_flexible_grasp_supervisor
{
template <class ContainerAllocator>
struct SetForceParamsRequest_
{
  typedef SetForceParamsRequest_<ContainerAllocator> Type;

  SetForceParamsRequest_()
    : contact_threshold(0.0)
    , target_force(0.0)
    , max_force(0.0)  {
    }
  SetForceParamsRequest_(const ContainerAllocator& _alloc)
    : contact_threshold(0.0)
    , target_force(0.0)
    , max_force(0.0)  {
  (void)_alloc;
    }



   typedef float _contact_threshold_type;
  _contact_threshold_type contact_threshold;

   typedef float _target_force_type;
  _target_force_type target_force;

   typedef float _max_force_type;
  _max_force_type max_force;





  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetForceParamsRequest_

typedef ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<std::allocator<void> > SetForceParamsRequest;

typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::SetForceParamsRequest > SetForceParamsRequestPtr;
typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::SetForceParamsRequest const> SetForceParamsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.contact_threshold == rhs.contact_threshold &&
    lhs.target_force == rhs.target_force &&
    lhs.max_force == rhs.max_force;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alicia_flexible_grasp_supervisor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "53d772afe2b788b2798fa44d853c5379";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x53d772afe2b788b2ULL;
  static const uint64_t static_value2 = 0x798fa44d853c5379ULL;
};

template<class ContainerAllocator>
struct DataType< ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/SetForceParamsRequest";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 contact_threshold\n"
"float32 target_force\n"
"float32 max_force\n"
;
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.contact_threshold);
      stream.next(m.target_force);
      stream.next(m.max_force);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetForceParamsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alicia_flexible_grasp_supervisor::SetForceParamsRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "contact_threshold: ";
    Printer<float>::stream(s, indent + "  ", v.contact_threshold);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_force: ";
    Printer<float>::stream(s, indent + "  ", v.target_force);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "max_force: ";
    Printer<float>::stream(s, indent + "  ", v.max_force);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SETFORCEPARAMSREQUEST_H
