// Generated by gencpp from file alicia_flexible_grasp_supervisor/SetFloat.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SETFLOAT_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SETFLOAT_H

#include <ros/service_traits.h>


#include <alicia_flexible_grasp_supervisor/SetFloatRequest.h>
#include <alicia_flexible_grasp_supervisor/SetFloatResponse.h>


namespace alicia_flexible_grasp_supervisor
{

struct SetFloat
{

typedef SetFloatRequest Request;
typedef SetFloatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFloat
} // namespace alicia_flexible_grasp_supervisor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::SetFloat > {
  static const char* value()
  {
    return "5d5778235c8477c5669230b433701e6c";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::SetFloat&) { return value(); }
};

template<>
struct DataType< ::alicia_flexible_grasp_supervisor::SetFloat > {
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/SetFloat";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::SetFloat&) { return value(); }
};


// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::SetFloatRequest> should match
// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::SetFloat >
template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::SetFloatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::alicia_flexible_grasp_supervisor::SetFloat >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::SetFloatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::alicia_flexible_grasp_supervisor::SetFloatRequest> should match
// service_traits::DataType< ::alicia_flexible_grasp_supervisor::SetFloat >
template<>
struct DataType< ::alicia_flexible_grasp_supervisor::SetFloatRequest>
{
  static const char* value()
  {
    return DataType< ::alicia_flexible_grasp_supervisor::SetFloat >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::SetFloatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::SetFloatResponse> should match
// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::SetFloat >
template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::SetFloatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::alicia_flexible_grasp_supervisor::SetFloat >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::SetFloatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::alicia_flexible_grasp_supervisor::SetFloatResponse> should match
// service_traits::DataType< ::alicia_flexible_grasp_supervisor::SetFloat >
template<>
struct DataType< ::alicia_flexible_grasp_supervisor::SetFloatResponse>
{
  static const char* value()
  {
    return DataType< ::alicia_flexible_grasp_supervisor::SetFloat >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::SetFloatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SETFLOAT_H
