// Generated by gencpp from file alicia_flexible_grasp_supervisor/SetJointCommand.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SETJOINTCOMMAND_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SETJOINTCOMMAND_H

#include <ros/service_traits.h>


#include <alicia_flexible_grasp_supervisor/SetJointCommandRequest.h>
#include <alicia_flexible_grasp_supervisor/SetJointCommandResponse.h>


namespace alicia_flexible_grasp_supervisor
{

struct SetJointCommand
{

typedef SetJointCommandRequest Request;
typedef SetJointCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointCommand
} // namespace alicia_flexible_grasp_supervisor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::SetJointCommand > {
  static const char* value()
  {
    return "b0bf18399157799d65e71152f45a1060";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::SetJointCommand&) { return value(); }
};

template<>
struct DataType< ::alicia_flexible_grasp_supervisor::SetJointCommand > {
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/SetJointCommand";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::SetJointCommand&) { return value(); }
};


// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::SetJointCommandRequest> should match
// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::SetJointCommand >
template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::SetJointCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::alicia_flexible_grasp_supervisor::SetJointCommand >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::SetJointCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::alicia_flexible_grasp_supervisor::SetJointCommandRequest> should match
// service_traits::DataType< ::alicia_flexible_grasp_supervisor::SetJointCommand >
template<>
struct DataType< ::alicia_flexible_grasp_supervisor::SetJointCommandRequest>
{
  static const char* value()
  {
    return DataType< ::alicia_flexible_grasp_supervisor::SetJointCommand >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::SetJointCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::SetJointCommandResponse> should match
// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::SetJointCommand >
template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::SetJointCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::alicia_flexible_grasp_supervisor::SetJointCommand >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::SetJointCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::alicia_flexible_grasp_supervisor::SetJointCommandResponse> should match
// service_traits::DataType< ::alicia_flexible_grasp_supervisor::SetJointCommand >
template<>
struct DataType< ::alicia_flexible_grasp_supervisor::SetJointCommandResponse>
{
  static const char* value()
  {
    return DataType< ::alicia_flexible_grasp_supervisor::SetJointCommand >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::SetJointCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SETJOINTCOMMAND_H
