// Generated by gencpp from file alicia_flexible_grasp_supervisor/SetJointCommandRequest.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SETJOINTCOMMANDREQUEST_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SETJOINTCOMMANDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alicia_flexible_grasp_supervisor
{
template <class ContainerAllocator>
struct SetJointCommandRequest_
{
  typedef SetJointCommandRequest_<ContainerAllocator> Type;

  SetJointCommandRequest_()
    : positions()
    , execute(false)  {
    }
  SetJointCommandRequest_(const ContainerAllocator& _alloc)
    : positions(_alloc)
    , execute(false)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _positions_type;
  _positions_type positions;

   typedef uint8_t _execute_type;
  _execute_type execute;





  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetJointCommandRequest_

typedef ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<std::allocator<void> > SetJointCommandRequest;

typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::SetJointCommandRequest > SetJointCommandRequestPtr;
typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::SetJointCommandRequest const> SetJointCommandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.positions == rhs.positions &&
    lhs.execute == rhs.execute;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alicia_flexible_grasp_supervisor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb8fa9bd70aafb9e8af7a7602e0d2ab5";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb8fa9bd70aafb9eULL;
  static const uint64_t static_value2 = 0x8af7a7602e0d2ab5ULL;
};

template<class ContainerAllocator>
struct DataType< ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/SetJointCommandRequest";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] positions\n"
"bool execute\n"
;
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.positions);
      stream.next(m.execute);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetJointCommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alicia_flexible_grasp_supervisor::SetJointCommandRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "positions: ";
    if (v.positions.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.positions[i]);
    }
    if (v.positions.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "execute: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.execute);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SETJOINTCOMMANDREQUEST_H
