// Generated by gencpp from file alicia_flexible_grasp_supervisor/SetTargetPose.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SETTARGETPOSE_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SETTARGETPOSE_H

#include <ros/service_traits.h>


#include <alicia_flexible_grasp_supervisor/SetTargetPoseRequest.h>
#include <alicia_flexible_grasp_supervisor/SetTargetPoseResponse.h>


namespace alicia_flexible_grasp_supervisor
{

struct SetTargetPose
{

typedef SetTargetPoseRequest Request;
typedef SetTargetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTargetPose
} // namespace alicia_flexible_grasp_supervisor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::SetTargetPose > {
  static const char* value()
  {
    return "00e64715c2cedd5add3400704911c3af";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::SetTargetPose&) { return value(); }
};

template<>
struct DataType< ::alicia_flexible_grasp_supervisor::SetTargetPose > {
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/SetTargetPose";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::SetTargetPose&) { return value(); }
};


// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest> should match
// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::SetTargetPose >
template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::alicia_flexible_grasp_supervisor::SetTargetPose >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest> should match
// service_traits::DataType< ::alicia_flexible_grasp_supervisor::SetTargetPose >
template<>
struct DataType< ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::alicia_flexible_grasp_supervisor::SetTargetPose >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::SetTargetPoseResponse> should match
// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::SetTargetPose >
template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::SetTargetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::alicia_flexible_grasp_supervisor::SetTargetPose >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::SetTargetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::alicia_flexible_grasp_supervisor::SetTargetPoseResponse> should match
// service_traits::DataType< ::alicia_flexible_grasp_supervisor::SetTargetPose >
template<>
struct DataType< ::alicia_flexible_grasp_supervisor::SetTargetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::alicia_flexible_grasp_supervisor::SetTargetPose >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::SetTargetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SETTARGETPOSE_H
