// Generated by gencpp from file alicia_flexible_grasp_supervisor/SetTargetPoseRequest.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SETTARGETPOSEREQUEST_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SETTARGETPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace alicia_flexible_grasp_supervisor
{
template <class ContainerAllocator>
struct SetTargetPoseRequest_
{
  typedef SetTargetPoseRequest_<ContainerAllocator> Type;

  SetTargetPoseRequest_()
    : pose()
    , execute(false)  {
    }
  SetTargetPoseRequest_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , execute(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef uint8_t _execute_type;
  _execute_type execute;





  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetTargetPoseRequest_

typedef ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<std::allocator<void> > SetTargetPoseRequest;

typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest > SetTargetPoseRequestPtr;
typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest const> SetTargetPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.execute == rhs.execute;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alicia_flexible_grasp_supervisor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6fc4fbc3eff3db2ecc3f08fd3533ebf8";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6fc4fbc3eff3db2eULL;
  static const uint64_t static_value2 = 0xcc3f08fd3533ebf8ULL;
};

template<class ContainerAllocator>
struct DataType< ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/SetTargetPoseRequest";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose\n"
"bool execute\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.execute);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTargetPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alicia_flexible_grasp_supervisor::SetTargetPoseRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "execute: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.execute);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_SETTARGETPOSEREQUEST_H
