// Generated by gencpp from file alicia_flexible_grasp_supervisor/StartGrasp.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_STARTGRASP_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_STARTGRASP_H

#include <ros/service_traits.h>


#include <alicia_flexible_grasp_supervisor/StartGraspRequest.h>
#include <alicia_flexible_grasp_supervisor/StartGraspResponse.h>


namespace alicia_flexible_grasp_supervisor
{

struct StartGrasp
{

typedef StartGraspRequest Request;
typedef StartGraspResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartGrasp
} // namespace alicia_flexible_grasp_supervisor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::StartGrasp > {
  static const char* value()
  {
    return "c1e3198b68b143183a952c85cd9f744a";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::StartGrasp&) { return value(); }
};

template<>
struct DataType< ::alicia_flexible_grasp_supervisor::StartGrasp > {
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/StartGrasp";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::StartGrasp&) { return value(); }
};


// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::StartGraspRequest> should match
// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::StartGrasp >
template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::StartGraspRequest>
{
  static const char* value()
  {
    return MD5Sum< ::alicia_flexible_grasp_supervisor::StartGrasp >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::StartGraspRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::alicia_flexible_grasp_supervisor::StartGraspRequest> should match
// service_traits::DataType< ::alicia_flexible_grasp_supervisor::StartGrasp >
template<>
struct DataType< ::alicia_flexible_grasp_supervisor::StartGraspRequest>
{
  static const char* value()
  {
    return DataType< ::alicia_flexible_grasp_supervisor::StartGrasp >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::StartGraspRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::StartGraspResponse> should match
// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::StartGrasp >
template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::StartGraspResponse>
{
  static const char* value()
  {
    return MD5Sum< ::alicia_flexible_grasp_supervisor::StartGrasp >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::StartGraspResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::alicia_flexible_grasp_supervisor::StartGraspResponse> should match
// service_traits::DataType< ::alicia_flexible_grasp_supervisor::StartGrasp >
template<>
struct DataType< ::alicia_flexible_grasp_supervisor::StartGraspResponse>
{
  static const char* value()
  {
    return DataType< ::alicia_flexible_grasp_supervisor::StartGrasp >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::StartGraspResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_STARTGRASP_H
