// Generated by gencpp from file alicia_flexible_grasp_supervisor/StartGraspResponse.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_STARTGRASPRESPONSE_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_STARTGRASPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alicia_flexible_grasp_supervisor
{
template <class ContainerAllocator>
struct StartGraspResponse_
{
  typedef StartGraspResponse_<ContainerAllocator> Type;

  StartGraspResponse_()
    : accepted(false)
    , message()  {
    }
  StartGraspResponse_(const ContainerAllocator& _alloc)
    : accepted(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _accepted_type;
  _accepted_type accepted;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StartGraspResponse_

typedef ::alicia_flexible_grasp_supervisor::StartGraspResponse_<std::allocator<void> > StartGraspResponse;

typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::StartGraspResponse > StartGraspResponsePtr;
typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::StartGraspResponse const> StartGraspResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator2> & rhs)
{
  return lhs.accepted == rhs.accepted &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alicia_flexible_grasp_supervisor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5273b27f74d9c0fd6d8a58d787fc7be7";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5273b27f74d9c0fdULL;
  static const uint64_t static_value2 = 0x6d8a58d787fc7be7ULL;
};

template<class ContainerAllocator>
struct DataType< ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/StartGraspResponse";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool accepted\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.accepted);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartGraspResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alicia_flexible_grasp_supervisor::StartGraspResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "accepted: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.accepted);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_STARTGRASPRESPONSE_H
