// Generated by gencpp from file alicia_flexible_grasp_supervisor/StartGraspRequest.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_STARTGRASPREQUEST_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_STARTGRASPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alicia_flexible_grasp_supervisor
{
template <class ContainerAllocator>
struct StartGraspRequest_
{
  typedef StartGraspRequest_<ContainerAllocator> Type;

  StartGraspRequest_()
    : use_latest_object(false)
    , object_label()  {
    }
  StartGraspRequest_(const ContainerAllocator& _alloc)
    : use_latest_object(false)
    , object_label(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _use_latest_object_type;
  _use_latest_object_type use_latest_object;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _object_label_type;
  _object_label_type object_label;





  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartGraspRequest_

typedef ::alicia_flexible_grasp_supervisor::StartGraspRequest_<std::allocator<void> > StartGraspRequest;

typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::StartGraspRequest > StartGraspRequestPtr;
typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::StartGraspRequest const> StartGraspRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator2> & rhs)
{
  return lhs.use_latest_object == rhs.use_latest_object &&
    lhs.object_label == rhs.object_label;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alicia_flexible_grasp_supervisor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8ddc0b68e4582dfda5c94d85249f9a8";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8ddc0b68e4582dfULL;
  static const uint64_t static_value2 = 0xda5c94d85249f9a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/StartGraspRequest";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool use_latest_object\n"
"string object_label\n"
;
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.use_latest_object);
      stream.next(m.object_label);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartGraspRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alicia_flexible_grasp_supervisor::StartGraspRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "use_latest_object: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_latest_object);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "object_label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.object_label);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_STARTGRASPREQUEST_H
