// Generated by gencpp from file alicia_flexible_grasp_supervisor/StopGraspRequest.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_STOPGRASPREQUEST_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_STOPGRASPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alicia_flexible_grasp_supervisor
{
template <class ContainerAllocator>
struct StopGraspRequest_
{
  typedef StopGraspRequest_<ContainerAllocator> Type;

  StopGraspRequest_()
    : emergency(false)  {
    }
  StopGraspRequest_(const ContainerAllocator& _alloc)
    : emergency(false)  {
  (void)_alloc;
    }



   typedef uint8_t _emergency_type;
  _emergency_type emergency;





  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StopGraspRequest_

typedef ::alicia_flexible_grasp_supervisor::StopGraspRequest_<std::allocator<void> > StopGraspRequest;

typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::StopGraspRequest > StopGraspRequestPtr;
typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::StopGraspRequest const> StopGraspRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator2> & rhs)
{
  return lhs.emergency == rhs.emergency;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alicia_flexible_grasp_supervisor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa208417948d3e0ac7bed355db544b81";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa208417948d3e0aULL;
  static const uint64_t static_value2 = 0xc7bed355db544b81ULL;
};

template<class ContainerAllocator>
struct DataType< ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/StopGraspRequest";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool emergency\n"
;
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.emergency);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopGraspRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alicia_flexible_grasp_supervisor::StopGraspRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "emergency: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emergency);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_STOPGRASPREQUEST_H
