// Generated by gencpp from file alicia_flexible_grasp_supervisor/StopGrasp.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_STOPGRASP_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_STOPGRASP_H

#include <ros/service_traits.h>


#include <alicia_flexible_grasp_supervisor/StopGraspRequest.h>
#include <alicia_flexible_grasp_supervisor/StopGraspResponse.h>


namespace alicia_flexible_grasp_supervisor
{

struct StopGrasp
{

typedef StopGraspRequest Request;
typedef StopGraspResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopGrasp
} // namespace alicia_flexible_grasp_supervisor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::StopGrasp > {
  static const char* value()
  {
    return "82bc3459aaf52f4d9d44d2af0299d950";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::StopGrasp&) { return value(); }
};

template<>
struct DataType< ::alicia_flexible_grasp_supervisor::StopGrasp > {
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/StopGrasp";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::StopGrasp&) { return value(); }
};


// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::StopGraspRequest> should match
// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::StopGrasp >
template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::StopGraspRequest>
{
  static const char* value()
  {
    return MD5Sum< ::alicia_flexible_grasp_supervisor::StopGrasp >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::StopGraspRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::alicia_flexible_grasp_supervisor::StopGraspRequest> should match
// service_traits::DataType< ::alicia_flexible_grasp_supervisor::StopGrasp >
template<>
struct DataType< ::alicia_flexible_grasp_supervisor::StopGraspRequest>
{
  static const char* value()
  {
    return DataType< ::alicia_flexible_grasp_supervisor::StopGrasp >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::StopGraspRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::StopGraspResponse> should match
// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::StopGrasp >
template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::StopGraspResponse>
{
  static const char* value()
  {
    return MD5Sum< ::alicia_flexible_grasp_supervisor::StopGrasp >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::StopGraspResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::alicia_flexible_grasp_supervisor::StopGraspResponse> should match
// service_traits::DataType< ::alicia_flexible_grasp_supervisor::StopGrasp >
template<>
struct DataType< ::alicia_flexible_grasp_supervisor::StopGraspResponse>
{
  static const char* value()
  {
    return DataType< ::alicia_flexible_grasp_supervisor::StopGrasp >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::StopGraspResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_STOPGRASP_H
