// Generated by gencpp from file alicia_flexible_grasp_supervisor/TactileFrame.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_TACTILEFRAME_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_TACTILEFRAME_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace alicia_flexible_grasp_supervisor
{
template <class ContainerAllocator>
struct TactileFrame_
{
  typedef TactileFrame_<ContainerAllocator> Type;

  TactileFrame_()
    : header()
    , skin_name()
    , values()
    , rows(0)
    , cols(0)
    , total_force_mn(0.0)
    , max_force_mn(0.0)
    , max_index(0)
    , center_x(0.0)
    , center_y(0.0)
    , contact(false)
    , valid(false)  {
    }
  TactileFrame_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , skin_name(_alloc)
    , values(_alloc)
    , rows(0)
    , cols(0)
    , total_force_mn(0.0)
    , max_force_mn(0.0)
    , max_index(0)
    , center_x(0.0)
    , center_y(0.0)
    , contact(false)
    , valid(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _skin_name_type;
  _skin_name_type skin_name;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _values_type;
  _values_type values;

   typedef uint32_t _rows_type;
  _rows_type rows;

   typedef uint32_t _cols_type;
  _cols_type cols;

   typedef float _total_force_mn_type;
  _total_force_mn_type total_force_mn;

   typedef float _max_force_mn_type;
  _max_force_mn_type max_force_mn;

   typedef uint32_t _max_index_type;
  _max_index_type max_index;

   typedef float _center_x_type;
  _center_x_type center_x;

   typedef float _center_y_type;
  _center_y_type center_y;

   typedef uint8_t _contact_type;
  _contact_type contact;

   typedef uint8_t _valid_type;
  _valid_type valid;





  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator> const> ConstPtr;

}; // struct TactileFrame_

typedef ::alicia_flexible_grasp_supervisor::TactileFrame_<std::allocator<void> > TactileFrame;

typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::TactileFrame > TactileFramePtr;
typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::TactileFrame const> TactileFrameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.skin_name == rhs.skin_name &&
    lhs.values == rhs.values &&
    lhs.rows == rhs.rows &&
    lhs.cols == rhs.cols &&
    lhs.total_force_mn == rhs.total_force_mn &&
    lhs.max_force_mn == rhs.max_force_mn &&
    lhs.max_index == rhs.max_index &&
    lhs.center_x == rhs.center_x &&
    lhs.center_y == rhs.center_y &&
    lhs.contact == rhs.contact &&
    lhs.valid == rhs.valid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alicia_flexible_grasp_supervisor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a144ff6b8561cbba1f903254a0728a98";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa144ff6b8561cbbaULL;
  static const uint64_t static_value2 = 0x1f903254a0728a98ULL;
};

template<class ContainerAllocator>
struct DataType< ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/TactileFrame";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string skin_name\n"
"float32[] values\n"
"uint32 rows\n"
"uint32 cols\n"
"float32 total_force_mn\n"
"float32 max_force_mn\n"
"uint32 max_index\n"
"float32 center_x\n"
"float32 center_y\n"
"bool contact\n"
"bool valid\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.skin_name);
      stream.next(m.values);
      stream.next(m.rows);
      stream.next(m.cols);
      stream.next(m.total_force_mn);
      stream.next(m.max_force_mn);
      stream.next(m.max_index);
      stream.next(m.center_x);
      stream.next(m.center_y);
      stream.next(m.contact);
      stream.next(m.valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TactileFrame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "skin_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.skin_name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "values: ";
    if (v.values.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.values[i]);
    }
    if (v.values.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rows: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.rows);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cols: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.cols);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "total_force_mn: ";
    Printer<float>::stream(s, indent + "  ", v.total_force_mn);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "max_force_mn: ";
    Printer<float>::stream(s, indent + "  ", v.max_force_mn);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "max_index: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.max_index);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "center_x: ";
    Printer<float>::stream(s, indent + "  ", v.center_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "center_y: ";
    Printer<float>::stream(s, indent + "  ", v.center_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "contact: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.contact);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_TACTILEFRAME_H
