// Generated by gencpp from file alicia_flexible_grasp_supervisor/TactileState.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_TACTILESTATE_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_TACTILESTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <alicia_flexible_grasp_supervisor/TactileFrame.h>
#include <alicia_flexible_grasp_supervisor/TactileFrame.h>

namespace alicia_flexible_grasp_supervisor
{
template <class ContainerAllocator>
struct TactileState_
{
  typedef TactileState_<ContainerAllocator> Type;

  TactileState_()
    : header()
    , left()
    , right()
    , total_grip_force_mn(0.0)
    , force_diff_mn(0.0)
    , left_contact(false)
    , right_contact(false)
    , object_grasped(false)
    , slip_detected(false)
    , valid(false)  {
    }
  TactileState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left(_alloc)
    , right(_alloc)
    , total_grip_force_mn(0.0)
    , force_diff_mn(0.0)
    , left_contact(false)
    , right_contact(false)
    , object_grasped(false)
    , slip_detected(false)
    , valid(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator>  _left_type;
  _left_type left;

   typedef  ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator>  _right_type;
  _right_type right;

   typedef float _total_grip_force_mn_type;
  _total_grip_force_mn_type total_grip_force_mn;

   typedef float _force_diff_mn_type;
  _force_diff_mn_type force_diff_mn;

   typedef uint8_t _left_contact_type;
  _left_contact_type left_contact;

   typedef uint8_t _right_contact_type;
  _right_contact_type right_contact;

   typedef uint8_t _object_grasped_type;
  _object_grasped_type object_grasped;

   typedef uint8_t _slip_detected_type;
  _slip_detected_type slip_detected;

   typedef uint8_t _valid_type;
  _valid_type valid;





  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator> const> ConstPtr;

}; // struct TactileState_

typedef ::alicia_flexible_grasp_supervisor::TactileState_<std::allocator<void> > TactileState;

typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::TactileState > TactileStatePtr;
typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::TactileState const> TactileStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.left == rhs.left &&
    lhs.right == rhs.right &&
    lhs.total_grip_force_mn == rhs.total_grip_force_mn &&
    lhs.force_diff_mn == rhs.force_diff_mn &&
    lhs.left_contact == rhs.left_contact &&
    lhs.right_contact == rhs.right_contact &&
    lhs.object_grasped == rhs.object_grasped &&
    lhs.slip_detected == rhs.slip_detected &&
    lhs.valid == rhs.valid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alicia_flexible_grasp_supervisor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5df6a8c43bd865ec0ec8d2f74fe1aa66";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5df6a8c43bd865ecULL;
  static const uint64_t static_value2 = 0x0ec8d2f74fe1aa66ULL;
};

template<class ContainerAllocator>
struct DataType< ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/TactileState";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"alicia_flexible_grasp_supervisor/TactileFrame left\n"
"alicia_flexible_grasp_supervisor/TactileFrame right\n"
"float32 total_grip_force_mn\n"
"float32 force_diff_mn\n"
"bool left_contact\n"
"bool right_contact\n"
"bool object_grasped\n"
"bool slip_detected\n"
"bool valid\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: alicia_flexible_grasp_supervisor/TactileFrame\n"
"std_msgs/Header header\n"
"string skin_name\n"
"float32[] values\n"
"uint32 rows\n"
"uint32 cols\n"
"float32 total_force_mn\n"
"float32 max_force_mn\n"
"uint32 max_index\n"
"float32 center_x\n"
"float32 center_y\n"
"bool contact\n"
"bool valid\n"
;
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left);
      stream.next(m.right);
      stream.next(m.total_grip_force_mn);
      stream.next(m.force_diff_mn);
      stream.next(m.left_contact);
      stream.next(m.right_contact);
      stream.next(m.object_grasped);
      stream.next(m.slip_detected);
      stream.next(m.valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TactileState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alicia_flexible_grasp_supervisor::TactileState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "left: ";
    Printer< ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator> >::stream(s, indent + "  ", v.left);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right: ";
    Printer< ::alicia_flexible_grasp_supervisor::TactileFrame_<ContainerAllocator> >::stream(s, indent + "  ", v.right);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "total_grip_force_mn: ";
    Printer<float>::stream(s, indent + "  ", v.total_grip_force_mn);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "force_diff_mn: ";
    Printer<float>::stream(s, indent + "  ", v.force_diff_mn);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "left_contact: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_contact);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_contact: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_contact);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "object_grasped: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.object_grasped);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "slip_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.slip_detected);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_TACTILESTATE_H
