// Generated by gencpp from file alicia_flexible_grasp_supervisor/TcpCalibrationCommand.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_TCPCALIBRATIONCOMMAND_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_TCPCALIBRATIONCOMMAND_H

#include <ros/service_traits.h>


#include <alicia_flexible_grasp_supervisor/TcpCalibrationCommandRequest.h>
#include <alicia_flexible_grasp_supervisor/TcpCalibrationCommandResponse.h>


namespace alicia_flexible_grasp_supervisor
{

struct TcpCalibrationCommand
{

typedef TcpCalibrationCommandRequest Request;
typedef TcpCalibrationCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TcpCalibrationCommand
} // namespace alicia_flexible_grasp_supervisor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommand > {
  static const char* value()
  {
    return "58e49899f0eda63c395f3d3908079771";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::TcpCalibrationCommand&) { return value(); }
};

template<>
struct DataType< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommand > {
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/TcpCalibrationCommand";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::TcpCalibrationCommand&) { return value(); }
};


// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandRequest> should match
// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommand >
template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommand >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandRequest> should match
// service_traits::DataType< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommand >
template<>
struct DataType< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandRequest>
{
  static const char* value()
  {
    return DataType< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommand >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse> should match
// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommand >
template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommand >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse> should match
// service_traits::DataType< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommand >
template<>
struct DataType< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse>
{
  static const char* value()
  {
    return DataType< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommand >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_TCPCALIBRATIONCOMMAND_H
