// Generated by gencpp from file alicia_flexible_grasp_supervisor/TcpCalibrationCommandResponse.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_TCPCALIBRATIONCOMMANDRESPONSE_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_TCPCALIBRATIONCOMMANDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace alicia_flexible_grasp_supervisor
{
template <class ContainerAllocator>
struct TcpCalibrationCommandResponse_
{
  typedef TcpCalibrationCommandResponse_<ContainerAllocator> Type;

  TcpCalibrationCommandResponse_()
    : success(false)
    , message()
    , sample_count(0)
    , tcp_translation()
    , fixed_point()
    , rms_error_m(0.0)
    , max_error_m(0.0)
    , orientation_span_deg(0.0)
    , result_file()  {
    }
  TcpCalibrationCommandResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , sample_count(0)
    , tcp_translation(_alloc)
    , fixed_point(_alloc)
    , rms_error_m(0.0)
    , max_error_m(0.0)
    , orientation_span_deg(0.0)
    , result_file(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef uint32_t _sample_count_type;
  _sample_count_type sample_count;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _tcp_translation_type;
  _tcp_translation_type tcp_translation;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _fixed_point_type;
  _fixed_point_type fixed_point;

   typedef double _rms_error_m_type;
  _rms_error_m_type rms_error_m;

   typedef double _max_error_m_type;
  _max_error_m_type max_error_m;

   typedef double _orientation_span_deg_type;
  _orientation_span_deg_type orientation_span_deg;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_file_type;
  _result_file_type result_file;





  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TcpCalibrationCommandResponse_

typedef ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<std::allocator<void> > TcpCalibrationCommandResponse;

typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse > TcpCalibrationCommandResponsePtr;
typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse const> TcpCalibrationCommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.sample_count == rhs.sample_count &&
    lhs.tcp_translation == rhs.tcp_translation &&
    lhs.fixed_point == rhs.fixed_point &&
    lhs.rms_error_m == rhs.rms_error_m &&
    lhs.max_error_m == rhs.max_error_m &&
    lhs.orientation_span_deg == rhs.orientation_span_deg &&
    lhs.result_file == rhs.result_file;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alicia_flexible_grasp_supervisor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "024a38e797fbdb70356ab0fa543ee5f5";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x024a38e797fbdb70ULL;
  static const uint64_t static_value2 = 0x356ab0fa543ee5f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/TcpCalibrationCommandResponse";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"uint32 sample_count\n"
"geometry_msgs/Vector3 tcp_translation\n"
"geometry_msgs/Vector3 fixed_point\n"
"float64 rms_error_m\n"
"float64 max_error_m\n"
"float64 orientation_span_deg\n"
"string result_file\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.sample_count);
      stream.next(m.tcp_translation);
      stream.next(m.fixed_point);
      stream.next(m.rms_error_m);
      stream.next(m.max_error_m);
      stream.next(m.orientation_span_deg);
      stream.next(m.result_file);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TcpCalibrationCommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alicia_flexible_grasp_supervisor::TcpCalibrationCommandResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sample_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.sample_count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tcp_translation: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.tcp_translation);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fixed_point: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.fixed_point);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rms_error_m: ";
    Printer<double>::stream(s, indent + "  ", v.rms_error_m);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "max_error_m: ";
    Printer<double>::stream(s, indent + "  ", v.max_error_m);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "orientation_span_deg: ";
    Printer<double>::stream(s, indent + "  ", v.orientation_span_deg);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "result_file: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result_file);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_TCPCALIBRATIONCOMMANDRESPONSE_H
