// Generated by gencpp from file alicia_flexible_grasp_supervisor/TriggerZeroResponse.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_TRIGGERZERORESPONSE_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_TRIGGERZERORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alicia_flexible_grasp_supervisor
{
template <class ContainerAllocator>
struct TriggerZeroResponse_
{
  typedef TriggerZeroResponse_<ContainerAllocator> Type;

  TriggerZeroResponse_()
    : ok(false)
    , message()  {
    }
  TriggerZeroResponse_(const ContainerAllocator& _alloc)
    : ok(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _ok_type;
  _ok_type ok;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TriggerZeroResponse_

typedef ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<std::allocator<void> > TriggerZeroResponse;

typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::TriggerZeroResponse > TriggerZeroResponsePtr;
typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::TriggerZeroResponse const> TriggerZeroResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ok == rhs.ok &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alicia_flexible_grasp_supervisor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6fcb3b1ed8c7743c7fb7d5bcca28513";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6fcb3b1ed8c7743ULL;
  static const uint64_t static_value2 = 0xc7fb7d5bcca28513ULL;
};

template<class ContainerAllocator>
struct DataType< ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/TriggerZeroResponse";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ok\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TriggerZeroResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alicia_flexible_grasp_supervisor::TriggerZeroResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ok);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_TRIGGERZERORESPONSE_H
