// Generated by gencpp from file alicia_flexible_grasp_supervisor/TriggerZeroRequest.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_TRIGGERZEROREQUEST_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_TRIGGERZEROREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alicia_flexible_grasp_supervisor
{
template <class ContainerAllocator>
struct TriggerZeroRequest_
{
  typedef TriggerZeroRequest_<ContainerAllocator> Type;

  TriggerZeroRequest_()
    : skin_id(0)  {
    }
  TriggerZeroRequest_(const ContainerAllocator& _alloc)
    : skin_id(0)  {
  (void)_alloc;
    }



   typedef uint8_t _skin_id_type;
  _skin_id_type skin_id;





  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TriggerZeroRequest_

typedef ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<std::allocator<void> > TriggerZeroRequest;

typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::TriggerZeroRequest > TriggerZeroRequestPtr;
typedef boost::shared_ptr< ::alicia_flexible_grasp_supervisor::TriggerZeroRequest const> TriggerZeroRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator2> & rhs)
{
  return lhs.skin_id == rhs.skin_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator1> & lhs, const ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace alicia_flexible_grasp_supervisor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7618ff84be9a52700a05bf68771d2fa5";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7618ff84be9a5270ULL;
  static const uint64_t static_value2 = 0x0a05bf68771d2fa5ULL;
};

template<class ContainerAllocator>
struct DataType< ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/TriggerZeroRequest";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 skin_id\n"
;
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.skin_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TriggerZeroRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alicia_flexible_grasp_supervisor::TriggerZeroRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "skin_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.skin_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_TRIGGERZEROREQUEST_H
