// Generated by gencpp from file alicia_flexible_grasp_supervisor/TriggerZero.msg
// DO NOT EDIT!


#ifndef ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_TRIGGERZERO_H
#define ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_TRIGGERZERO_H

#include <ros/service_traits.h>


#include <alicia_flexible_grasp_supervisor/TriggerZeroRequest.h>
#include <alicia_flexible_grasp_supervisor/TriggerZeroResponse.h>


namespace alicia_flexible_grasp_supervisor
{

struct TriggerZero
{

typedef TriggerZeroRequest Request;
typedef TriggerZeroResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TriggerZero
} // namespace alicia_flexible_grasp_supervisor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::TriggerZero > {
  static const char* value()
  {
    return "1531357144714babf83a2def976015d9";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::TriggerZero&) { return value(); }
};

template<>
struct DataType< ::alicia_flexible_grasp_supervisor::TriggerZero > {
  static const char* value()
  {
    return "alicia_flexible_grasp_supervisor/TriggerZero";
  }

  static const char* value(const ::alicia_flexible_grasp_supervisor::TriggerZero&) { return value(); }
};


// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::TriggerZeroRequest> should match
// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::TriggerZero >
template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::TriggerZeroRequest>
{
  static const char* value()
  {
    return MD5Sum< ::alicia_flexible_grasp_supervisor::TriggerZero >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::TriggerZeroRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::alicia_flexible_grasp_supervisor::TriggerZeroRequest> should match
// service_traits::DataType< ::alicia_flexible_grasp_supervisor::TriggerZero >
template<>
struct DataType< ::alicia_flexible_grasp_supervisor::TriggerZeroRequest>
{
  static const char* value()
  {
    return DataType< ::alicia_flexible_grasp_supervisor::TriggerZero >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::TriggerZeroRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::TriggerZeroResponse> should match
// service_traits::MD5Sum< ::alicia_flexible_grasp_supervisor::TriggerZero >
template<>
struct MD5Sum< ::alicia_flexible_grasp_supervisor::TriggerZeroResponse>
{
  static const char* value()
  {
    return MD5Sum< ::alicia_flexible_grasp_supervisor::TriggerZero >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::TriggerZeroResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::alicia_flexible_grasp_supervisor::TriggerZeroResponse> should match
// service_traits::DataType< ::alicia_flexible_grasp_supervisor::TriggerZero >
template<>
struct DataType< ::alicia_flexible_grasp_supervisor::TriggerZeroResponse>
{
  static const char* value()
  {
    return DataType< ::alicia_flexible_grasp_supervisor::TriggerZero >::value();
  }
  static const char* value(const ::alicia_flexible_grasp_supervisor::TriggerZeroResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALICIA_FLEXIBLE_GRASP_SUPERVISOR_MESSAGE_TRIGGERZERO_H
