# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from alicia_flexible_grasp_supervisor/Grasp6DPlan.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import alicia_flexible_grasp_supervisor.msg
import geometry_msgs.msg
import std_msgs.msg

class Grasp6DPlan(genpy.Message):
  _md5sum = "a90c722154d42b08b0800cd88d52ff9d"
  _type = "alicia_flexible_grasp_supervisor/Grasp6DPlan"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
bool valid
geometry_msgs/Pose[] poses
float32 score
float32 candidate_width_m
float32 required_open_width_m
alicia_flexible_grasp_supervisor/ObjectGeometry object_geometry
string model_choice
string plan_id
string diagnostic

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: alicia_flexible_grasp_supervisor/ObjectGeometry
std_msgs/Header header
bool valid
string label
string source_mode
geometry_msgs/Pose pose_base
geometry_msgs/Vector3 size_xyz_m
geometry_msgs/Vector3 support_normal_base
float32 support_offset_m
uint32 valid_depth_points
float32 valid_depth_ratio
float32 depth_mad_m
uint32 fused_frames
float32 support_inlier_ratio
uint32 object_point_count
string failure_reason

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','valid','poses','score','candidate_width_m','required_open_width_m','object_geometry','model_choice','plan_id','diagnostic']
  _slot_types = ['std_msgs/Header','bool','geometry_msgs/Pose[]','float32','float32','float32','alicia_flexible_grasp_supervisor/ObjectGeometry','string','string','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,valid,poses,score,candidate_width_m,required_open_width_m,object_geometry,model_choice,plan_id,diagnostic

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Grasp6DPlan, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.valid is None:
        self.valid = False
      if self.poses is None:
        self.poses = []
      if self.score is None:
        self.score = 0.
      if self.candidate_width_m is None:
        self.candidate_width_m = 0.
      if self.required_open_width_m is None:
        self.required_open_width_m = 0.
      if self.object_geometry is None:
        self.object_geometry = alicia_flexible_grasp_supervisor.msg.ObjectGeometry()
      if self.model_choice is None:
        self.model_choice = ''
      if self.plan_id is None:
        self.plan_id = ''
      if self.diagnostic is None:
        self.diagnostic = ''
    else:
      self.header = std_msgs.msg.Header()
      self.valid = False
      self.poses = []
      self.score = 0.
      self.candidate_width_m = 0.
      self.required_open_width_m = 0.
      self.object_geometry = alicia_flexible_grasp_supervisor.msg.ObjectGeometry()
      self.model_choice = ''
      self.plan_id = ''
      self.diagnostic = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.valid
      buff.write(_get_struct_B().pack(_x))
      length = len(self.poses)
      buff.write(_struct_I.pack(length))
      for val1 in self.poses:
        _v1 = val1.position
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v2 = val1.orientation
        _x = _v2
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
      _x = self
      buff.write(_get_struct_3f3I().pack(_x.score, _x.candidate_width_m, _x.required_open_width_m, _x.object_geometry.header.seq, _x.object_geometry.header.stamp.secs, _x.object_geometry.header.stamp.nsecs))
      _x = self.object_geometry.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.object_geometry.valid
      buff.write(_get_struct_B().pack(_x))
      _x = self.object_geometry.label
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.object_geometry.source_mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_13dfI2fIfI().pack(_x.object_geometry.pose_base.position.x, _x.object_geometry.pose_base.position.y, _x.object_geometry.pose_base.position.z, _x.object_geometry.pose_base.orientation.x, _x.object_geometry.pose_base.orientation.y, _x.object_geometry.pose_base.orientation.z, _x.object_geometry.pose_base.orientation.w, _x.object_geometry.size_xyz_m.x, _x.object_geometry.size_xyz_m.y, _x.object_geometry.size_xyz_m.z, _x.object_geometry.support_normal_base.x, _x.object_geometry.support_normal_base.y, _x.object_geometry.support_normal_base.z, _x.object_geometry.support_offset_m, _x.object_geometry.valid_depth_points, _x.object_geometry.valid_depth_ratio, _x.object_geometry.depth_mad_m, _x.object_geometry.fused_frames, _x.object_geometry.support_inlier_ratio, _x.object_geometry.object_point_count))
      _x = self.object_geometry.failure_reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.model_choice
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.plan_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.diagnostic
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.poses is None:
        self.poses = None
      if self.object_geometry is None:
        self.object_geometry = alicia_flexible_grasp_supervisor.msg.ObjectGeometry()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.valid,) = _get_struct_B().unpack(str[start:end])
      self.valid = bool(self.valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.poses = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose()
        _v3 = val1.position
        _x = _v3
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v4 = val1.orientation
        _x = _v4
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        self.poses.append(val1)
      _x = self
      start = end
      end += 24
      (_x.score, _x.candidate_width_m, _x.required_open_width_m, _x.object_geometry.header.seq, _x.object_geometry.header.stamp.secs, _x.object_geometry.header.stamp.nsecs,) = _get_struct_3f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_geometry.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_geometry.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.object_geometry.valid,) = _get_struct_B().unpack(str[start:end])
      self.object_geometry.valid = bool(self.object_geometry.valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_geometry.label = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_geometry.label = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_geometry.source_mode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_geometry.source_mode = str[start:end]
      _x = self
      start = end
      end += 132
      (_x.object_geometry.pose_base.position.x, _x.object_geometry.pose_base.position.y, _x.object_geometry.pose_base.position.z, _x.object_geometry.pose_base.orientation.x, _x.object_geometry.pose_base.orientation.y, _x.object_geometry.pose_base.orientation.z, _x.object_geometry.pose_base.orientation.w, _x.object_geometry.size_xyz_m.x, _x.object_geometry.size_xyz_m.y, _x.object_geometry.size_xyz_m.z, _x.object_geometry.support_normal_base.x, _x.object_geometry.support_normal_base.y, _x.object_geometry.support_normal_base.z, _x.object_geometry.support_offset_m, _x.object_geometry.valid_depth_points, _x.object_geometry.valid_depth_ratio, _x.object_geometry.depth_mad_m, _x.object_geometry.fused_frames, _x.object_geometry.support_inlier_ratio, _x.object_geometry.object_point_count,) = _get_struct_13dfI2fIfI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_geometry.failure_reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_geometry.failure_reason = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.model_choice = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.model_choice = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.plan_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.plan_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.diagnostic = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.diagnostic = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.valid
      buff.write(_get_struct_B().pack(_x))
      length = len(self.poses)
      buff.write(_struct_I.pack(length))
      for val1 in self.poses:
        _v5 = val1.position
        _x = _v5
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v6 = val1.orientation
        _x = _v6
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
      _x = self
      buff.write(_get_struct_3f3I().pack(_x.score, _x.candidate_width_m, _x.required_open_width_m, _x.object_geometry.header.seq, _x.object_geometry.header.stamp.secs, _x.object_geometry.header.stamp.nsecs))
      _x = self.object_geometry.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.object_geometry.valid
      buff.write(_get_struct_B().pack(_x))
      _x = self.object_geometry.label
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.object_geometry.source_mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_13dfI2fIfI().pack(_x.object_geometry.pose_base.position.x, _x.object_geometry.pose_base.position.y, _x.object_geometry.pose_base.position.z, _x.object_geometry.pose_base.orientation.x, _x.object_geometry.pose_base.orientation.y, _x.object_geometry.pose_base.orientation.z, _x.object_geometry.pose_base.orientation.w, _x.object_geometry.size_xyz_m.x, _x.object_geometry.size_xyz_m.y, _x.object_geometry.size_xyz_m.z, _x.object_geometry.support_normal_base.x, _x.object_geometry.support_normal_base.y, _x.object_geometry.support_normal_base.z, _x.object_geometry.support_offset_m, _x.object_geometry.valid_depth_points, _x.object_geometry.valid_depth_ratio, _x.object_geometry.depth_mad_m, _x.object_geometry.fused_frames, _x.object_geometry.support_inlier_ratio, _x.object_geometry.object_point_count))
      _x = self.object_geometry.failure_reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.model_choice
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.plan_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.diagnostic
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.poses is None:
        self.poses = None
      if self.object_geometry is None:
        self.object_geometry = alicia_flexible_grasp_supervisor.msg.ObjectGeometry()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.valid,) = _get_struct_B().unpack(str[start:end])
      self.valid = bool(self.valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.poses = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose()
        _v7 = val1.position
        _x = _v7
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v8 = val1.orientation
        _x = _v8
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        self.poses.append(val1)
      _x = self
      start = end
      end += 24
      (_x.score, _x.candidate_width_m, _x.required_open_width_m, _x.object_geometry.header.seq, _x.object_geometry.header.stamp.secs, _x.object_geometry.header.stamp.nsecs,) = _get_struct_3f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_geometry.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_geometry.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.object_geometry.valid,) = _get_struct_B().unpack(str[start:end])
      self.object_geometry.valid = bool(self.object_geometry.valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_geometry.label = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_geometry.label = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_geometry.source_mode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_geometry.source_mode = str[start:end]
      _x = self
      start = end
      end += 132
      (_x.object_geometry.pose_base.position.x, _x.object_geometry.pose_base.position.y, _x.object_geometry.pose_base.position.z, _x.object_geometry.pose_base.orientation.x, _x.object_geometry.pose_base.orientation.y, _x.object_geometry.pose_base.orientation.z, _x.object_geometry.pose_base.orientation.w, _x.object_geometry.size_xyz_m.x, _x.object_geometry.size_xyz_m.y, _x.object_geometry.size_xyz_m.z, _x.object_geometry.support_normal_base.x, _x.object_geometry.support_normal_base.y, _x.object_geometry.support_normal_base.z, _x.object_geometry.support_offset_m, _x.object_geometry.valid_depth_points, _x.object_geometry.valid_depth_ratio, _x.object_geometry.depth_mad_m, _x.object_geometry.fused_frames, _x.object_geometry.support_inlier_ratio, _x.object_geometry.object_point_count,) = _get_struct_13dfI2fIfI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_geometry.failure_reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_geometry.failure_reason = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.model_choice = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.model_choice = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.plan_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.plan_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.diagnostic = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.diagnostic = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_13dfI2fIfI = None
def _get_struct_13dfI2fIfI():
    global _struct_13dfI2fIfI
    if _struct_13dfI2fIfI is None:
        _struct_13dfI2fIfI = struct.Struct("<13dfI2fIfI")
    return _struct_13dfI2fIfI
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_3f3I = None
def _get_struct_3f3I():
    global _struct_3f3I
    if _struct_3f3I is None:
        _struct_3f3I = struct.Struct("<3f3I")
    return _struct_3f3I
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
