# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from alicia_flexible_grasp_supervisor/ObjectGeometry.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class ObjectGeometry(genpy.Message):
  _md5sum = "be6e291b8f028ecb31c9e9f8f891dc32"
  _type = "alicia_flexible_grasp_supervisor/ObjectGeometry"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
bool valid
string label
string source_mode
geometry_msgs/Pose pose_base
geometry_msgs/Vector3 size_xyz_m
geometry_msgs/Vector3 support_normal_base
float32 support_offset_m
uint32 valid_depth_points
float32 valid_depth_ratio
float32 depth_mad_m
uint32 fused_frames
float32 support_inlier_ratio
uint32 object_point_count
string failure_reason

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','valid','label','source_mode','pose_base','size_xyz_m','support_normal_base','support_offset_m','valid_depth_points','valid_depth_ratio','depth_mad_m','fused_frames','support_inlier_ratio','object_point_count','failure_reason']
  _slot_types = ['std_msgs/Header','bool','string','string','geometry_msgs/Pose','geometry_msgs/Vector3','geometry_msgs/Vector3','float32','uint32','float32','float32','uint32','float32','uint32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,valid,label,source_mode,pose_base,size_xyz_m,support_normal_base,support_offset_m,valid_depth_points,valid_depth_ratio,depth_mad_m,fused_frames,support_inlier_ratio,object_point_count,failure_reason

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ObjectGeometry, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.valid is None:
        self.valid = False
      if self.label is None:
        self.label = ''
      if self.source_mode is None:
        self.source_mode = ''
      if self.pose_base is None:
        self.pose_base = geometry_msgs.msg.Pose()
      if self.size_xyz_m is None:
        self.size_xyz_m = geometry_msgs.msg.Vector3()
      if self.support_normal_base is None:
        self.support_normal_base = geometry_msgs.msg.Vector3()
      if self.support_offset_m is None:
        self.support_offset_m = 0.
      if self.valid_depth_points is None:
        self.valid_depth_points = 0
      if self.valid_depth_ratio is None:
        self.valid_depth_ratio = 0.
      if self.depth_mad_m is None:
        self.depth_mad_m = 0.
      if self.fused_frames is None:
        self.fused_frames = 0
      if self.support_inlier_ratio is None:
        self.support_inlier_ratio = 0.
      if self.object_point_count is None:
        self.object_point_count = 0
      if self.failure_reason is None:
        self.failure_reason = ''
    else:
      self.header = std_msgs.msg.Header()
      self.valid = False
      self.label = ''
      self.source_mode = ''
      self.pose_base = geometry_msgs.msg.Pose()
      self.size_xyz_m = geometry_msgs.msg.Vector3()
      self.support_normal_base = geometry_msgs.msg.Vector3()
      self.support_offset_m = 0.
      self.valid_depth_points = 0
      self.valid_depth_ratio = 0.
      self.depth_mad_m = 0.
      self.fused_frames = 0
      self.support_inlier_ratio = 0.
      self.object_point_count = 0
      self.failure_reason = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.valid
      buff.write(_get_struct_B().pack(_x))
      _x = self.label
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.source_mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_13dfI2fIfI().pack(_x.pose_base.position.x, _x.pose_base.position.y, _x.pose_base.position.z, _x.pose_base.orientation.x, _x.pose_base.orientation.y, _x.pose_base.orientation.z, _x.pose_base.orientation.w, _x.size_xyz_m.x, _x.size_xyz_m.y, _x.size_xyz_m.z, _x.support_normal_base.x, _x.support_normal_base.y, _x.support_normal_base.z, _x.support_offset_m, _x.valid_depth_points, _x.valid_depth_ratio, _x.depth_mad_m, _x.fused_frames, _x.support_inlier_ratio, _x.object_point_count))
      _x = self.failure_reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose_base is None:
        self.pose_base = geometry_msgs.msg.Pose()
      if self.size_xyz_m is None:
        self.size_xyz_m = geometry_msgs.msg.Vector3()
      if self.support_normal_base is None:
        self.support_normal_base = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.valid,) = _get_struct_B().unpack(str[start:end])
      self.valid = bool(self.valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.label = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.label = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.source_mode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.source_mode = str[start:end]
      _x = self
      start = end
      end += 132
      (_x.pose_base.position.x, _x.pose_base.position.y, _x.pose_base.position.z, _x.pose_base.orientation.x, _x.pose_base.orientation.y, _x.pose_base.orientation.z, _x.pose_base.orientation.w, _x.size_xyz_m.x, _x.size_xyz_m.y, _x.size_xyz_m.z, _x.support_normal_base.x, _x.support_normal_base.y, _x.support_normal_base.z, _x.support_offset_m, _x.valid_depth_points, _x.valid_depth_ratio, _x.depth_mad_m, _x.fused_frames, _x.support_inlier_ratio, _x.object_point_count,) = _get_struct_13dfI2fIfI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.failure_reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.failure_reason = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.valid
      buff.write(_get_struct_B().pack(_x))
      _x = self.label
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.source_mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_13dfI2fIfI().pack(_x.pose_base.position.x, _x.pose_base.position.y, _x.pose_base.position.z, _x.pose_base.orientation.x, _x.pose_base.orientation.y, _x.pose_base.orientation.z, _x.pose_base.orientation.w, _x.size_xyz_m.x, _x.size_xyz_m.y, _x.size_xyz_m.z, _x.support_normal_base.x, _x.support_normal_base.y, _x.support_normal_base.z, _x.support_offset_m, _x.valid_depth_points, _x.valid_depth_ratio, _x.depth_mad_m, _x.fused_frames, _x.support_inlier_ratio, _x.object_point_count))
      _x = self.failure_reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose_base is None:
        self.pose_base = geometry_msgs.msg.Pose()
      if self.size_xyz_m is None:
        self.size_xyz_m = geometry_msgs.msg.Vector3()
      if self.support_normal_base is None:
        self.support_normal_base = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.valid,) = _get_struct_B().unpack(str[start:end])
      self.valid = bool(self.valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.label = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.label = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.source_mode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.source_mode = str[start:end]
      _x = self
      start = end
      end += 132
      (_x.pose_base.position.x, _x.pose_base.position.y, _x.pose_base.position.z, _x.pose_base.orientation.x, _x.pose_base.orientation.y, _x.pose_base.orientation.z, _x.pose_base.orientation.w, _x.size_xyz_m.x, _x.size_xyz_m.y, _x.size_xyz_m.z, _x.support_normal_base.x, _x.support_normal_base.y, _x.support_normal_base.z, _x.support_offset_m, _x.valid_depth_points, _x.valid_depth_ratio, _x.depth_mad_m, _x.fused_frames, _x.support_inlier_ratio, _x.object_point_count,) = _get_struct_13dfI2fIfI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.failure_reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.failure_reason = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_13dfI2fIfI = None
def _get_struct_13dfI2fIfI():
    global _struct_13dfI2fIfI
    if _struct_13dfI2fIfI is None:
        _struct_13dfI2fIfI = struct.Struct("<13dfI2fIfI")
    return _struct_13dfI2fIfI
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
