# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from alicia_flexible_grasp_supervisor/ObjectPose.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class ObjectPose(genpy.Message):
  _md5sum = "2d3731316703d38acb9f83ae0dd46e90"
  _type = "alicia_flexible_grasp_supervisor/ObjectPose"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
bool detected
string label
float32 confidence
uint32 u
uint32 v
uint32 bbox_x
uint32 bbox_y
uint32 bbox_width
uint32 bbox_height
float32 depth_m
geometry_msgs/PoseStamped pose_camera
geometry_msgs/PoseStamped pose_base

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['header','detected','label','confidence','u','v','bbox_x','bbox_y','bbox_width','bbox_height','depth_m','pose_camera','pose_base']
  _slot_types = ['std_msgs/Header','bool','string','float32','uint32','uint32','uint32','uint32','uint32','uint32','float32','geometry_msgs/PoseStamped','geometry_msgs/PoseStamped']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,detected,label,confidence,u,v,bbox_x,bbox_y,bbox_width,bbox_height,depth_m,pose_camera,pose_base

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ObjectPose, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.detected is None:
        self.detected = False
      if self.label is None:
        self.label = ''
      if self.confidence is None:
        self.confidence = 0.
      if self.u is None:
        self.u = 0
      if self.v is None:
        self.v = 0
      if self.bbox_x is None:
        self.bbox_x = 0
      if self.bbox_y is None:
        self.bbox_y = 0
      if self.bbox_width is None:
        self.bbox_width = 0
      if self.bbox_height is None:
        self.bbox_height = 0
      if self.depth_m is None:
        self.depth_m = 0.
      if self.pose_camera is None:
        self.pose_camera = geometry_msgs.msg.PoseStamped()
      if self.pose_base is None:
        self.pose_base = geometry_msgs.msg.PoseStamped()
    else:
      self.header = std_msgs.msg.Header()
      self.detected = False
      self.label = ''
      self.confidence = 0.
      self.u = 0
      self.v = 0
      self.bbox_x = 0
      self.bbox_y = 0
      self.bbox_width = 0
      self.bbox_height = 0
      self.depth_m = 0.
      self.pose_camera = geometry_msgs.msg.PoseStamped()
      self.pose_base = geometry_msgs.msg.PoseStamped()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.detected
      buff.write(_get_struct_B().pack(_x))
      _x = self.label
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_f6If3I().pack(_x.confidence, _x.u, _x.v, _x.bbox_x, _x.bbox_y, _x.bbox_width, _x.bbox_height, _x.depth_m, _x.pose_camera.header.seq, _x.pose_camera.header.stamp.secs, _x.pose_camera.header.stamp.nsecs))
      _x = self.pose_camera.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.pose_camera.pose.position.x, _x.pose_camera.pose.position.y, _x.pose_camera.pose.position.z, _x.pose_camera.pose.orientation.x, _x.pose_camera.pose.orientation.y, _x.pose_camera.pose.orientation.z, _x.pose_camera.pose.orientation.w, _x.pose_base.header.seq, _x.pose_base.header.stamp.secs, _x.pose_base.header.stamp.nsecs))
      _x = self.pose_base.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.pose_base.pose.position.x, _x.pose_base.pose.position.y, _x.pose_base.pose.position.z, _x.pose_base.pose.orientation.x, _x.pose_base.pose.orientation.y, _x.pose_base.pose.orientation.z, _x.pose_base.pose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose_camera is None:
        self.pose_camera = geometry_msgs.msg.PoseStamped()
      if self.pose_base is None:
        self.pose_base = geometry_msgs.msg.PoseStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.detected,) = _get_struct_B().unpack(str[start:end])
      self.detected = bool(self.detected)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.label = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.label = str[start:end]
      _x = self
      start = end
      end += 44
      (_x.confidence, _x.u, _x.v, _x.bbox_x, _x.bbox_y, _x.bbox_width, _x.bbox_height, _x.depth_m, _x.pose_camera.header.seq, _x.pose_camera.header.stamp.secs, _x.pose_camera.header.stamp.nsecs,) = _get_struct_f6If3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pose_camera.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pose_camera.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.pose_camera.pose.position.x, _x.pose_camera.pose.position.y, _x.pose_camera.pose.position.z, _x.pose_camera.pose.orientation.x, _x.pose_camera.pose.orientation.y, _x.pose_camera.pose.orientation.z, _x.pose_camera.pose.orientation.w, _x.pose_base.header.seq, _x.pose_base.header.stamp.secs, _x.pose_base.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pose_base.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pose_base.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.pose_base.pose.position.x, _x.pose_base.pose.position.y, _x.pose_base.pose.position.z, _x.pose_base.pose.orientation.x, _x.pose_base.pose.orientation.y, _x.pose_base.pose.orientation.z, _x.pose_base.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.detected
      buff.write(_get_struct_B().pack(_x))
      _x = self.label
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_f6If3I().pack(_x.confidence, _x.u, _x.v, _x.bbox_x, _x.bbox_y, _x.bbox_width, _x.bbox_height, _x.depth_m, _x.pose_camera.header.seq, _x.pose_camera.header.stamp.secs, _x.pose_camera.header.stamp.nsecs))
      _x = self.pose_camera.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.pose_camera.pose.position.x, _x.pose_camera.pose.position.y, _x.pose_camera.pose.position.z, _x.pose_camera.pose.orientation.x, _x.pose_camera.pose.orientation.y, _x.pose_camera.pose.orientation.z, _x.pose_camera.pose.orientation.w, _x.pose_base.header.seq, _x.pose_base.header.stamp.secs, _x.pose_base.header.stamp.nsecs))
      _x = self.pose_base.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.pose_base.pose.position.x, _x.pose_base.pose.position.y, _x.pose_base.pose.position.z, _x.pose_base.pose.orientation.x, _x.pose_base.pose.orientation.y, _x.pose_base.pose.orientation.z, _x.pose_base.pose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose_camera is None:
        self.pose_camera = geometry_msgs.msg.PoseStamped()
      if self.pose_base is None:
        self.pose_base = geometry_msgs.msg.PoseStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.detected,) = _get_struct_B().unpack(str[start:end])
      self.detected = bool(self.detected)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.label = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.label = str[start:end]
      _x = self
      start = end
      end += 44
      (_x.confidence, _x.u, _x.v, _x.bbox_x, _x.bbox_y, _x.bbox_width, _x.bbox_height, _x.depth_m, _x.pose_camera.header.seq, _x.pose_camera.header.stamp.secs, _x.pose_camera.header.stamp.nsecs,) = _get_struct_f6If3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pose_camera.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pose_camera.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.pose_camera.pose.position.x, _x.pose_camera.pose.position.y, _x.pose_camera.pose.position.z, _x.pose_camera.pose.orientation.x, _x.pose_camera.pose.orientation.y, _x.pose_camera.pose.orientation.z, _x.pose_camera.pose.orientation.w, _x.pose_base.header.seq, _x.pose_base.header.stamp.secs, _x.pose_base.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pose_base.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pose_base.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.pose_base.pose.position.x, _x.pose_base.pose.position.y, _x.pose_base.pose.position.z, _x.pose_base.pose.orientation.x, _x.pose_base.pose.orientation.y, _x.pose_base.pose.orientation.z, _x.pose_base.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
_struct_7d3I = None
def _get_struct_7d3I():
    global _struct_7d3I
    if _struct_7d3I is None:
        _struct_7d3I = struct.Struct("<7d3I")
    return _struct_7d3I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_f6If3I = None
def _get_struct_f6If3I():
    global _struct_f6If3I
    if _struct_f6If3I is None:
        _struct_f6If3I = struct.Struct("<f6If3I")
    return _struct_f6If3I
