# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from alicia_flexible_grasp_supervisor/SafetyState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class SafetyState(genpy.Message):
  _md5sum = "d422c2c3e9933ef7c15274804ca0c2f7"
  _type = "alicia_flexible_grasp_supervisor/SafetyState"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
bool ok
bool emergency_stop
bool force_over_limit
bool robot_timeout
bool tactile_timeout
bool camera_timeout
bool planning_failed
string level
string message

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','ok','emergency_stop','force_over_limit','robot_timeout','tactile_timeout','camera_timeout','planning_failed','level','message']
  _slot_types = ['std_msgs/Header','bool','bool','bool','bool','bool','bool','bool','string','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,ok,emergency_stop,force_over_limit,robot_timeout,tactile_timeout,camera_timeout,planning_failed,level,message

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SafetyState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ok is None:
        self.ok = False
      if self.emergency_stop is None:
        self.emergency_stop = False
      if self.force_over_limit is None:
        self.force_over_limit = False
      if self.robot_timeout is None:
        self.robot_timeout = False
      if self.tactile_timeout is None:
        self.tactile_timeout = False
      if self.camera_timeout is None:
        self.camera_timeout = False
      if self.planning_failed is None:
        self.planning_failed = False
      if self.level is None:
        self.level = ''
      if self.message is None:
        self.message = ''
    else:
      self.header = std_msgs.msg.Header()
      self.ok = False
      self.emergency_stop = False
      self.force_over_limit = False
      self.robot_timeout = False
      self.tactile_timeout = False
      self.camera_timeout = False
      self.planning_failed = False
      self.level = ''
      self.message = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7B().pack(_x.ok, _x.emergency_stop, _x.force_over_limit, _x.robot_timeout, _x.tactile_timeout, _x.camera_timeout, _x.planning_failed))
      _x = self.level
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.message
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 7
      (_x.ok, _x.emergency_stop, _x.force_over_limit, _x.robot_timeout, _x.tactile_timeout, _x.camera_timeout, _x.planning_failed,) = _get_struct_7B().unpack(str[start:end])
      self.ok = bool(self.ok)
      self.emergency_stop = bool(self.emergency_stop)
      self.force_over_limit = bool(self.force_over_limit)
      self.robot_timeout = bool(self.robot_timeout)
      self.tactile_timeout = bool(self.tactile_timeout)
      self.camera_timeout = bool(self.camera_timeout)
      self.planning_failed = bool(self.planning_failed)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.level = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.level = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.message = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.message = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7B().pack(_x.ok, _x.emergency_stop, _x.force_over_limit, _x.robot_timeout, _x.tactile_timeout, _x.camera_timeout, _x.planning_failed))
      _x = self.level
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.message
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 7
      (_x.ok, _x.emergency_stop, _x.force_over_limit, _x.robot_timeout, _x.tactile_timeout, _x.camera_timeout, _x.planning_failed,) = _get_struct_7B().unpack(str[start:end])
      self.ok = bool(self.ok)
      self.emergency_stop = bool(self.emergency_stop)
      self.force_over_limit = bool(self.force_over_limit)
      self.robot_timeout = bool(self.robot_timeout)
      self.tactile_timeout = bool(self.tactile_timeout)
      self.camera_timeout = bool(self.camera_timeout)
      self.planning_failed = bool(self.planning_failed)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.level = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.level = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.message = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.message = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7B = None
def _get_struct_7B():
    global _struct_7B
    if _struct_7B is None:
        _struct_7B = struct.Struct("<7B")
    return _struct_7B
