# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from alicia_flexible_grasp_supervisor/TcpCalibrationCommandRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class TcpCalibrationCommandRequest(genpy.Message):
  _md5sum = "cba5e21e920a3a2b7b375cb65b64cdea"
  _type = "alicia_flexible_grasp_supervisor/TcpCalibrationCommandRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string command
"""
  __slots__ = ['command']
  _slot_types = ['string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       command

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TcpCalibrationCommandRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.command is None:
        self.command = ''
    else:
      self.command = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.command
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.command = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.command = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.command
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.command = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.command = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from alicia_flexible_grasp_supervisor/TcpCalibrationCommandResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class TcpCalibrationCommandResponse(genpy.Message):
  _md5sum = "024a38e797fbdb70356ab0fa543ee5f5"
  _type = "alicia_flexible_grasp_supervisor/TcpCalibrationCommandResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool success
string message
uint32 sample_count
geometry_msgs/Vector3 tcp_translation
geometry_msgs/Vector3 fixed_point
float64 rms_error_m
float64 max_error_m
float64 orientation_span_deg
string result_file


================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['success','message','sample_count','tcp_translation','fixed_point','rms_error_m','max_error_m','orientation_span_deg','result_file']
  _slot_types = ['bool','string','uint32','geometry_msgs/Vector3','geometry_msgs/Vector3','float64','float64','float64','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       success,message,sample_count,tcp_translation,fixed_point,rms_error_m,max_error_m,orientation_span_deg,result_file

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TcpCalibrationCommandResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.success is None:
        self.success = False
      if self.message is None:
        self.message = ''
      if self.sample_count is None:
        self.sample_count = 0
      if self.tcp_translation is None:
        self.tcp_translation = geometry_msgs.msg.Vector3()
      if self.fixed_point is None:
        self.fixed_point = geometry_msgs.msg.Vector3()
      if self.rms_error_m is None:
        self.rms_error_m = 0.
      if self.max_error_m is None:
        self.max_error_m = 0.
      if self.orientation_span_deg is None:
        self.orientation_span_deg = 0.
      if self.result_file is None:
        self.result_file = ''
    else:
      self.success = False
      self.message = ''
      self.sample_count = 0
      self.tcp_translation = geometry_msgs.msg.Vector3()
      self.fixed_point = geometry_msgs.msg.Vector3()
      self.rms_error_m = 0.
      self.max_error_m = 0.
      self.orientation_span_deg = 0.
      self.result_file = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.success
      buff.write(_get_struct_B().pack(_x))
      _x = self.message
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_I9d().pack(_x.sample_count, _x.tcp_translation.x, _x.tcp_translation.y, _x.tcp_translation.z, _x.fixed_point.x, _x.fixed_point.y, _x.fixed_point.z, _x.rms_error_m, _x.max_error_m, _x.orientation_span_deg))
      _x = self.result_file
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.tcp_translation is None:
        self.tcp_translation = geometry_msgs.msg.Vector3()
      if self.fixed_point is None:
        self.fixed_point = geometry_msgs.msg.Vector3()
      end = 0
      start = end
      end += 1
      (self.success,) = _get_struct_B().unpack(str[start:end])
      self.success = bool(self.success)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.message = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.message = str[start:end]
      _x = self
      start = end
      end += 76
      (_x.sample_count, _x.tcp_translation.x, _x.tcp_translation.y, _x.tcp_translation.z, _x.fixed_point.x, _x.fixed_point.y, _x.fixed_point.z, _x.rms_error_m, _x.max_error_m, _x.orientation_span_deg,) = _get_struct_I9d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.result_file = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.result_file = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.success
      buff.write(_get_struct_B().pack(_x))
      _x = self.message
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_I9d().pack(_x.sample_count, _x.tcp_translation.x, _x.tcp_translation.y, _x.tcp_translation.z, _x.fixed_point.x, _x.fixed_point.y, _x.fixed_point.z, _x.rms_error_m, _x.max_error_m, _x.orientation_span_deg))
      _x = self.result_file
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.tcp_translation is None:
        self.tcp_translation = geometry_msgs.msg.Vector3()
      if self.fixed_point is None:
        self.fixed_point = geometry_msgs.msg.Vector3()
      end = 0
      start = end
      end += 1
      (self.success,) = _get_struct_B().unpack(str[start:end])
      self.success = bool(self.success)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.message = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.message = str[start:end]
      _x = self
      start = end
      end += 76
      (_x.sample_count, _x.tcp_translation.x, _x.tcp_translation.y, _x.tcp_translation.z, _x.fixed_point.x, _x.fixed_point.y, _x.fixed_point.z, _x.rms_error_m, _x.max_error_m, _x.orientation_span_deg,) = _get_struct_I9d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.result_file = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.result_file = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_I9d = None
def _get_struct_I9d():
    global _struct_I9d
    if _struct_I9d is None:
        _struct_I9d = struct.Struct("<I9d")
    return _struct_I9d
class TcpCalibrationCommand(object):
  _type          = 'alicia_flexible_grasp_supervisor/TcpCalibrationCommand'
  _md5sum = '58e49899f0eda63c395f3d3908079771'
  _request_class  = TcpCalibrationCommandRequest
  _response_class = TcpCalibrationCommandResponse
