(cl:in-package alicia_flexible_grasp_supervisor-msg)
(cl:export '(HEADER-VAL
          HEADER
          VALID-VAL
          VALID
          LABEL-VAL
          LABEL
          SOURCE_MODE-VAL
          SOURCE_MODE
          POSE_BASE-VAL
          POSE_BASE
          SIZE_XYZ_M-VAL
          SIZE_XYZ_M
          SUPPORT_NORMAL_BASE-VAL
          SUPPORT_NORMAL_BASE
          SUPPORT_OFFSET_M-VAL
          SUPPORT_OFFSET_M
          VALID_DEPTH_POINTS-VAL
          VALID_DEPTH_POINTS
          VALID_DEPTH_RATIO-VAL
          VALID_DEPTH_RATIO
          DEPTH_MAD_M-VAL
          DEPTH_MAD_M
          FUSED_FRAMES-VAL
          FUSED_FRAMES
          SUPPORT_INLIER_RATIO-VAL
          SUPPORT_INLIER_RATIO
          OBJECT_POINT_COUNT-VAL
          OBJECT_POINT_COUNT
          FAILURE_REASON-VAL
          FAILURE_REASON
))