cmake_minimum_required(VERSION 3.0.2)
project(alicia_grasp_modes)
find_package(catkin REQUIRED COMPONENTS rospy std_msgs std_srvs sensor_msgs geometry_msgs message_filters tf2_ros cv_bridge message_generation alicia_flexible_grasp_supervisor)
catkin_python_setup()
add_service_files(FILES SetGraspMode.srv)
generate_messages()
catkin_package(CATKIN_DEPENDS message_runtime)
catkin_install_python(PROGRAMS scripts/unknown_tabletop_perception.py scripts/mode_router.py scripts/mode_aware_remote_grasp6d.py scripts/mode_aware_grasp_task.py scripts/switch_grasp_mode.py scripts/mode_aware_gui.py scripts/mode_aware_grasp_runner.py DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
install(DIRECTORY launch DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION})
